select
cast(uuid as string ),--uuid
cast(medorgid as string ),--医疗机构id
cast(medorgcode as string ),--医疗机构代码
cast(medorgname as string ),--医疗机构名称
cast(empiid as string ),--人员唯一标识id
cast(empino as string ),--人员唯一标识号
cast(persid as string ),--人员id
cast(persno as string ),--人员号
cast(visitid as string ),--就诊id
cast(visitno as string ),--就诊号
cast(serialno as string ),--流水号
cast(persname as string ),--人员姓名
cast(beinhospdate as date ),--在院日期
cast(repdate as string ),--快照日期
cast(reptime as string ),--快照时间
cast(repdttm as string ),--快照日期时间
cast(rephour as string ),--快照时刻
cast(newest as string),
cast(bednoid as string ),--床号id
cast(bedno as string ),--床号
cast(inhospdate as string ),--入院日期
cast(inhospwardid as string ),--入院护理单元编码
cast(inhospwardcode as string ),--入院护理单元编码
cast(inhospwardname as string ),--入院护理单元名称
cast(inhospmedelementid as string ),--入院医疗单元id
cast(inhospmedelementcode as string ),--入院医疗单元编码
cast(inhospmedelementname as string ),--入院医疗单元名称
cast(currentwardid as string ),--当前护理单元id
cast(currentwardcode as string ),--当前护理单元编码
cast(currentwardname as string ),--当前护理单元名称
cast(currentmedelementid as string ),--当前医疗单元id
cast(currentmedelementcode as string ),--当前医疗单元编码
cast(currentmedelementname as string ),--当前医疗单元名称
cast(currentstaffgroupid as string ),--当前医疗组长id
cast(currentstaffgroupcode as string ),--当前医疗组长工号
cast(currentstaffgroupname as string ),--当前医疗组长名称
cast(iswait as string ),--是否等待区
cast(beinhospperscount as int ),--在院人次
cast(datasourceflag as string ),--数据来源标识
cast(dstable as string ),--接入数据源的表
cast(indatasourcekey as string ),--接入数据源的key
cast(indatasourcekeyvalue as string ),--接入数据源的key值
cast(isdelete as string ),--是否物理删除
cast(lastupdatedttm as string ),--最后更新时间
cast(datacreatedttm as string ),--数据创建时间
cast(threecode as string ),--三级院区编码
cast(threename as string ),--三级院区名称
cast(omthreecode as string ),--运管院区编码
cast(omthreename as string), --运管院区名称
cast(omdeptid as string ),--运管科室id
cast(omdeptcode as string ),--运管科室编码
cast(omdeptdesc as string) --运管科室名称
from temp_mdr_beinhosp