#!/usr/bin/env python3
"""Export each figure of the submission manuscript as a standalone vector PDF.

MDPI asks for figures as separate files at production. All five are drawn in TikZ
and pgfplots inside main_applsci_mdpicls.tex, so this script lifts each drawing
out with the preamble fragments it needs and compiles it on its own, cropped to
the artwork by the preview package.

The drawing code is copied verbatim - the same rule as cn_floats.py. If an
exported figure differed from the one in the paper, the separate files would be
worse than not supplying them.

    python3 make_figs.py            # report what it would build
    python3 make_figs.py --write    # write figs/*.tex and compile figs/*.pdf

standalone.cls is not on this machine (TeX Live 2013); preview.sty is, and gives
the same crop without needing ghostscript.
"""
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TEX = os.path.join(HERE, "main_applsci_mdpicls.tex")
OUT = os.path.join(HERE, "figs")

# MDPI's applsci measure. The figures are sized against it (fig:preproc asks for
# 0.44\linewidth), so a standalone build has to reproduce it or the panels come
# out at the wrong size.
# MDPI's applsci measure, and the wider one a figure gets when the class wraps it
# in adjustwidth{-\extralength}{0cm} (mdpi.cls sets \extralength to 4.61cm).
MEASURE = "13.4cm"
MEASURE_WIDE = "18.01cm"

PREAMBLE_PARTS = [
    (r"\\usepackage\{pgfplots\}.*?\\usetikzlibrary\{[^}]*\}", "pgfplots + libraries"),
    (r"%---------------- Okabe-Ito.*?\\definecolor\{okGold\}\{HTML\}\{8C6D31\}",
     "colour palette"),
    (r"\\newcommand\{\\panel\}\[2\]\{[^\n]*", "panel label macro"),
]

HEAD = r"""%% GENERATED by make_figs.py - do not edit. Regenerate after changing the figure
%% in main_applsci_mdpicls.tex, or the separate file and the paper will disagree.
\documentclass[10pt]{article}
\usepackage[T1]{fontenc}
\usepackage{amsmath,amssymb}
\usepackage[active,tightpage]{preview}
%% The wide figures are wrapped in mdpi.cls's adjustwidth, which extends them
%% \extralength into the margin. Supplying the same length (mdpi.cls uses 4.61cm)
%% is what makes an exported figure the size it is in the paper; dropping the
%% wrapper instead would export it narrower than what the reader sees.
\usepackage{changepage}
\newlength{\extralength}\setlength{\extralength}{4.61cm}
%(parts)s
\setlength{\textwidth}{%(measure)s}
\setlength{\linewidth}{%(measure)s}
\pagestyle{empty}
\PreviewEnvironment{tikzpicture}
\begin{document}
%(body)s
\end{document}
"""


def figure_blocks(src):
    """label -> the drawing code of that figure (everything before \\caption)."""
    out = {}
    for m in re.finditer(r"\\begin\{figure\}(\*?)(.*?)\\end\{figure\}\1", src, re.S):
        blk = m.group(2)
        lab = re.search(r"\\label\{([^}]*)\}", blk)
        if not lab:
            continue
        cut = blk.find("\\caption{")
        art = blk[:cut] if cut > 0 else blk
        # The class wraps wide figures in adjustwidth, and its \end comes AFTER the
        # caption - cutting at the caption left the environment open. Drop the
        # wrapper and carry its effect in the page measure instead.
        wide = "\\begin{adjustwidth}" in art
        art = re.sub(r"\\begin\{adjustwidth\}\{[^}]*\}\{[^}]*\}", "", art)
        art = re.sub(r"\\end\{adjustwidth\}", "", art)
        art = re.sub(r"\\centering|\\vspace\{[^}]*\}", "", art).strip()
        out[lab.group(1)] = (art, wide)
    return out


def main():
    # Comment-only lines are deleted outright, not blanked: a blank line inside a
    # groupplot environment ends the paragraph and pgfplots aborts with
    # "Paragraph ended before \pgfplots@@environment@groupplot was complete".
    raw0 = open(TEX, encoding="utf-8").read()
    src = re.sub(r"(?m)^[ \t]*%(?!%).*\n", "", raw0)
    src = re.sub(r"(?<!\\)%(?!%).*", "", src)
    raw = raw0

    parts = []
    for pat, what in PREAMBLE_PARTS:
        m = re.search(pat, raw, re.S)
        if not m:
            sys.exit("preamble fragment not found: %s" % what)
        parts.append(m.group(0))
    preamble = "\n".join(parts)

    figs = figure_blocks(src)
    if not figs:
        sys.exit("no labelled figures found in %s" % os.path.basename(TEX))

    if "--write" not in sys.argv:
        for lab, (art, wide) in sorted(figs.items()):
            print("  would build figs/%s.pdf  (%d lines%s)"
                  % (lab.replace(":", "-"), art.count("\n") + 1,
                     ", wide measure" if wide else ""))
        print("\n(report only; pass --write to build)")
        return 0

    if not os.path.isdir(OUT):
        os.makedirs(OUT)
    fails = []
    for lab, (art, wide) in sorted(figs.items()):
        stem = lab.replace(":", "-")
        path = os.path.join(OUT, stem + ".tex")
        open(path, "w", encoding="utf-8").write(
            HEAD % dict(parts=preamble,
                        measure=MEASURE_WIDE if wide else MEASURE, body=art))
        for _ in range(2):
            subprocess.call(["pdflatex", "-interaction=nonstopmode",
                             "-output-directory", OUT, path],
                            stdout=open(os.devnull, "w"),
                            stderr=subprocess.STDOUT)
        pdf = os.path.join(OUT, stem + ".pdf")
        log = os.path.join(OUT, stem + ".log")
        errs = 0
        if os.path.exists(log):
            errs = open(log, encoding="utf-8", errors="replace").read().count("\n! ")
        if not os.path.exists(pdf) or errs:
            fails.append((stem, errs))
            print("  FAIL  %-16s errors=%d" % (stem, errs))
            continue
        size = subprocess.check_output(["pdfinfo", pdf]).decode()
        dims = re.search(r"Page size:\s*([\d.]+) x ([\d.]+)", size)
        print("  ok    %-16s %s pt x %s pt" % (stem, dims.group(1), dims.group(2))
              if dims else "  ok    %s" % stem)
    for junk in os.listdir(OUT):
        if junk.endswith((".aux", ".log")):
            os.remove(os.path.join(OUT, junk))
    if fails:
        print("\n%d figure(s) failed to build" % len(fails))
        return 1
    print("\n%d standalone figure PDFs in figs/" % len(figs))
    return 0


if __name__ == "__main__":
    sys.exit(main())
