-- =============================================================================
-- order_main 全字段输出：病区三列用「无 CTLOC_Type 限制」新逻辑；新增开单人科室三列（OEORI_UserDepartment_DR→CT_Loc）
-- 血缘：与 医嘱dc-公卫.sql 外层 SELECT 列顺序对齐；对应集成院区 HID0122 + HID0123（省公卫两院区）
--   HID0122 → hid0122_cache_his_dhcapp_sqluser.OE_OrdItem + CT_Loc（w22 / ud22）
--   HID0123 → hid0123_cache_his_dhcapp_sqluser.OE_OrdItem + CT_Loc（w23 / ud23）
-- 关联：order_main_dstablekey='OEORI_RowId' AND order_main_dstablevalue=OEORI_RowId
--       病区：CT_Loc = OEORI_AdmLoc_DR；开单人科室：CT_Loc = OEORI_UserDepartment_DR
-- 说明：列名大小写按集群调整；不修改医嘱dc-公卫.sql
-- =============================================================================

SELECT
  om.order_main_abtusereason AS order_main_abtusereason,
  om.order_main_applyid AS order_main_applyid,
  om.order_main_applytypecode AS order_main_applytypecode,
  om.order_main_applytypeid AS order_main_applytypeid,
  om.order_main_applytypename AS order_main_applytypename,
  om.order_main_basedrugflag AS order_main_basedrugflag,
  om.order_main_basicunit AS order_main_basicunit,
  om.order_main_basicunitratio AS order_main_basicunitratio,
  om.order_main_canceldttm AS order_main_canceldttm,
  om.order_main_cancelperscode AS order_main_cancelperscode,
  om.order_main_cancelpersid AS order_main_cancelpersid,
  om.order_main_cancelpersname AS order_main_cancelpersname,
  om.order_main_checkdttm AS order_main_checkdttm,
  om.order_main_checknurscode AS order_main_checknurscode,
  om.order_main_checknursid AS order_main_checknursid,
  om.order_main_checknursname AS order_main_checknursname,
  om.order_main_checkperscode AS order_main_checkperscode,
  om.order_main_checkpersid AS order_main_checkpersid,
  om.order_main_checkpersname AS order_main_checkpersname,
  om.order_main_datacreatedttm AS order_main_datacreatedttm,
  om.order_main_datasourceflag AS order_main_datasourceflag,
  om.order_main_dayonenum AS order_main_dayonenum,
  om.order_main_deptcode AS order_main_deptcode,
  om.order_main_deptid AS order_main_deptid,
  om.order_main_deptname AS order_main_deptname,
  om.order_main_dosingflag AS order_main_dosingflag,
  om.order_main_doubtorderdesc AS order_main_doubtorderdesc,
  om.order_main_doubtorderflag AS order_main_doubtorderflag,
  om.order_main_drugcode AS order_main_drugcode,
  om.order_main_drugdosageform AS order_main_drugdosageform,
  om.order_main_drugdosageformid AS order_main_drugdosageformid,
  om.order_main_drugid AS order_main_drugid,
  om.order_main_drugmanageplatformcode AS order_main_drugmanageplatformcode,
  om.order_main_drugname AS order_main_drugname,
  om.order_main_drugpurchasecode AS order_main_drugpurchasecode,
  om.order_main_drugspec AS order_main_drugspec,
  om.order_main_dstable AS order_main_dstable,
  om.order_main_dstablekey AS order_main_dstablekey,
  om.order_main_dstablevalue AS order_main_dstablevalue,
  om.order_main_empiid AS order_main_empiid,
  om.order_main_empino AS order_main_empino,
  om.order_main_enabledaynum AS order_main_enabledaynum,
  om.order_main_entrust AS order_main_entrust,
  om.order_main_entryreason AS order_main_entryreason,
  om.order_main_estimatedtotalprice AS order_main_estimatedtotalprice,
  om.order_main_excessreason AS order_main_excessreason,
  om.order_main_execdttm AS order_main_execdttm,
  om.order_main_execperscode AS order_main_execperscode,
  om.order_main_execpersid AS order_main_execpersid,
  om.order_main_execpersname AS order_main_execpersname,
  om.order_main_extdate1 AS order_main_extdate1,
  om.order_main_extdate2 AS order_main_extdate2,
  om.order_main_extnum1 AS order_main_extnum1,
  om.order_main_extnum2 AS order_main_extnum2,
  om.order_main_extstr1 AS order_main_extstr1,
  om.order_main_extstr2 AS order_main_extstr2,
  om.order_main_extstr3 AS order_main_extstr3,
  om.order_main_extstr4 AS order_main_extstr4,
  om.order_main_extstr5 AS order_main_extstr5,
  om.order_main_extstr6 AS order_main_extstr6,
  om.order_main_giveadaptationdisease AS order_main_giveadaptationdisease,
  om.order_main_givefreqcode AS order_main_givefreqcode,
  om.order_main_givefreqid AS order_main_givefreqid,
  om.order_main_givefreqname AS order_main_givefreqname,
  om.order_main_giverateunit AS order_main_giverateunit,
  om.order_main_giveratevalue AS order_main_giveratevalue,
  om.order_main_givestrength AS order_main_givestrength,
  om.order_main_givestrengthunit AS order_main_givestrengthunit,
  om.order_main_herbclasscode AS order_main_herbclasscode,
  om.order_main_herbclassid AS order_main_herbclassid,
  om.order_main_herbclassname AS order_main_herbclassname,
  om.order_main_herbdecoctioncode AS order_main_herbdecoctioncode,
  om.order_main_herbdecoctionid AS order_main_herbdecoctionid,
  om.order_main_herbdecoctionname AS order_main_herbdecoctionname,
  om.order_main_incisiontypecode AS order_main_incisiontypecode,
  om.order_main_incisiontypeid AS order_main_incisiontypeid,
  om.order_main_incisiontypename AS order_main_incisiontypename,
  om.order_main_insuflag AS order_main_insuflag,
  om.order_main_isdeleted AS order_main_isdeleted,
  om.order_main_lastupdatedttm AS order_main_lastupdatedttm,
  om.order_main_longorderrelationid AS order_main_longorderrelationid,
  om.order_main_maindrug AS order_main_maindrug,
  om.order_main_mainorderno AS order_main_mainorderno,
  om.order_main_materialsbarcode AS order_main_materialsbarcode,
  om.order_main_medorgcode AS order_main_medorgcode,
  om.order_main_medorgname AS order_main_medorgname,
  om.order_main_opspecialdiseasecode AS order_main_opspecialdiseasecode,
  om.order_main_opspecialdiseaseflag AS order_main_opspecialdiseaseflag,
  om.order_main_opspecialdiseaseid AS order_main_opspecialdiseaseid,
  om.order_main_opspecialdiseasename AS order_main_opspecialdiseasename,
  om.order_main_orderbegindttm AS order_main_orderbegindttm,
  om.order_main_ordercontent AS order_main_ordercontent,
  om.order_main_orderdetid AS order_main_orderdetid,
  om.order_main_orderdoctcode AS order_main_orderdoctcode,
  om.order_main_orderdoctid AS order_main_orderdoctid,
  om.order_main_orderdoctname AS order_main_orderdoctname,
  om.order_main_orderdttm AS order_main_orderdttm,
  om.order_main_orderenddttm AS order_main_orderenddttm,
  om.order_main_ordergroupno AS order_main_ordergroupno,
  om.order_main_ordergroupsubno AS order_main_ordergroupsubno,
  om.order_main_orderid AS order_main_orderid,
  om.order_main_orderitemcode AS order_main_orderitemcode,
  om.order_main_orderitemid AS order_main_orderitemid,
  om.order_main_orderitemname AS order_main_orderitemname,
  om.order_main_orderpclasscode AS order_main_orderpclasscode,
  om.order_main_orderpclassid AS order_main_orderpclassid,
  om.order_main_orderpclassname AS order_main_orderpclassname,
  om.order_main_orderrelationno AS order_main_orderrelationno,
  om.order_main_ordersclasscode AS order_main_ordersclasscode,
  om.order_main_ordersclassid AS order_main_ordersclassid,
  om.order_main_ordersclassname AS order_main_ordersclassname,
  om.order_main_orderserialno AS order_main_orderserialno,
  om.order_main_orderstagecode AS order_main_orderstagecode,
  om.order_main_orderstageid AS order_main_orderstageid,
  om.order_main_orderstagename AS order_main_orderstagename,
  om.order_main_orderstatuscode AS order_main_orderstatuscode,
  om.order_main_orderstatusid AS order_main_orderstatusid,
  om.order_main_orderstatusname AS order_main_orderstatusname,
  om.order_main_ordertypecode AS order_main_ordertypecode,
  om.order_main_ordertypeid AS order_main_ordertypeid,
  om.order_main_ordertypename AS order_main_ordertypename,
  om.order_main_outhospdrugflag AS order_main_outhospdrugflag,
  om.order_main_packageunit AS order_main_packageunit,
  om.order_main_packageunitratio AS order_main_packageunitratio,
  om.order_main_pathwaycode AS order_main_pathwaycode,
  om.order_main_pathwayid AS order_main_pathwayid,
  om.order_main_pathwayname AS order_main_pathwayname,
  om.order_main_paystatuscode AS order_main_paystatuscode,
  om.order_main_paystatusid AS order_main_paystatusid,
  om.order_main_paystatusname AS order_main_paystatusname,
  om.order_main_persid AS order_main_persid,
  om.order_main_persno AS order_main_persno,
  om.order_main_prescno AS order_main_prescno,
  om.order_main_presctypecode AS order_main_presctypecode,
  om.order_main_presctypeid AS order_main_presctypeid,
  om.order_main_presctypename AS order_main_presctypename,
  om.order_main_priority AS order_main_priority,
  om.order_main_recdeptcode AS order_main_recdeptcode,
  om.order_main_recdeptid AS order_main_recdeptid,
  om.order_main_recdeptname AS order_main_recdeptname,
  om.order_main_selfdrugflag AS order_main_selfdrugflag,
  om.order_main_skintest AS order_main_skintest,
  om.order_main_skintestmemo AS order_main_skintestmemo,
  om.order_main_specimenid AS order_main_specimenid,
  om.order_main_specimenname AS order_main_specimenname,
  om.order_main_textorderproperty AS order_main_textorderproperty,
  om.order_main_tisaneflag AS order_main_tisaneflag,
  om.order_main_totalmeasure AS order_main_totalmeasure,
  om.order_main_totalmeasureunit AS order_main_totalmeasureunit,
  om.order_main_totalprice AS order_main_totalprice,
  om.order_main_transfusionnum AS order_main_transfusionnum,
  om.order_main_treatmentcode AS order_main_treatmentcode,
  om.order_main_treatmentdesc AS order_main_treatmentdesc,
  om.order_main_treatmentid AS order_main_treatmentid,
  om.order_main_unitprice AS order_main_unitprice,
  om.order_main_unitypurchaseplatformflag AS order_main_unitypurchaseplatformflag,
  om.order_main_urgent AS order_main_urgent,
  om.order_main_usage AS order_main_usage,
  om.order_main_usedrugnum AS order_main_usedrugnum,
  om.order_main_usedrugpurpose AS order_main_usedrugpurpose,
  om.order_main_visitid AS order_main_visitid,
  om.order_main_visitno AS order_main_visitno,
  om.order_main_visittypecode AS order_main_visittypecode,
  om.order_main_visittypeid AS order_main_visittypeid,
  om.order_main_visittypename AS order_main_visittypename,
  CAST(COALESCE(ud22.ctloc_code, ud23.ctloc_code) AS VARCHAR) AS order_main_orderuserdept_code,
  CAST(COALESCE(ud22.ctloc_rowid, ud23.ctloc_rowid) AS VARCHAR) AS order_main_orderuserdept_id,
  CAST(COALESCE(ud22.ctloc_desc, ud23.ctloc_desc) AS VARCHAR) AS order_main_orderuserdept_name,
  -- 病区三列：新逻辑（不限制 CTLOC_Type），替代原 order_main 中同名列
  CAST(COALESCE(w22.ctloc_code, w23.ctloc_code) AS VARCHAR) AS order_main_wardcode,
  CAST(COALESCE(w22.ctloc_rowid, w23.ctloc_rowid) AS VARCHAR) AS order_main_wardid,
  CAST(COALESCE(w22.ctloc_desc, w23.ctloc_desc) AS VARCHAR) AS order_main_wardname,
  om.rowkey AS rowkey
FROM datacenter_db.order_main om
LEFT JOIN hid0122_cache_his_dhcapp_sqluser.oe_orditem o22
  ON om.medorgcode = 'HID0122'
 AND om.order_main_dstablevalue = o22.oeori_rowid
 AND o22.isdeleted = '0'
LEFT JOIN hid0122_cache_his_dhcapp_sqluser.ct_loc w22
  ON om.medorgcode = 'HID0122'
 AND w22.ctloc_rowid = o22.oeori_admloc_dr
LEFT JOIN hid0122_cache_his_dhcapp_sqluser.ct_loc ud22
  ON om.medorgcode = 'HID0122'
 AND ud22.ctloc_rowid = o22.oeori_userdepartment_dr
LEFT JOIN hid0123_cache_his_dhcapp_sqluser.oe_orditem o23
  ON om.medorgcode = 'HID0123'
 AND om.order_main_dstablevalue = o23.oeori_rowid
 AND o23.isdeleted = '0'
LEFT JOIN hid0123_cache_his_dhcapp_sqluser.ct_loc w23
  ON om.medorgcode = 'HID0123'
 AND w23.ctloc_rowid = o23.oeori_admloc_dr
LEFT JOIN hid0123_cache_his_dhcapp_sqluser.ct_loc ud23
  ON om.medorgcode = 'HID0123'
 AND ud23.ctloc_rowid = o23.oeori_userdepartment_dr
WHERE om.order_main_dstablekey = 'OEORI_RowId'
  AND om.medorgcode IN ('HID0122', 'HID0123');

-- 仅单院区：AND om.medorgcode = 'HID0122'，并去掉 o23/w23/ud23 JOIN
-- 若列名需双引号大写，将 om.xxx / o22 / w22 改为与 show columns 一致
