-- currentzyxz_v3 全量建表（含 HID0123/HID0124）
-- 院区：HID0101/0103/0117/0120/0122/0123/0124
-- hid0123 库两院区：ct_loc.ctloc_hospital_dr 2→HID0123，12→HID0124
-- 已有 MV 需 DROP 后重建，异步 MV 不支持直接改 AS 定义

CREATE MATERIALIZED VIEW `indicators`.`currentzyxz_v3` (`hosp_code`, `paadm_depcode_dr`, `ctloc_code`, `ctloc_desc`, `ward_code`, `ward_desc`, `sszyresult`, `lastupdatedttm`, `rowkey`)
COMMENT "实时在院人次"
DISTRIBUTED BY HASH(`hosp_code`)
REFRESH ASYNC EVERY(INTERVAL 180 SECOND)
PROPERTIES (
"replicated_storage" = "true",
"replication_num" = "3",
"storage_medium" = "HDD"
)
AS SELECT `a`.`hosp_code`, `a`.`paadm_depcode_dr`, `a`.`ctloc_code`, `a`.`ctloc_desc`, `a`.`ward_code`, `a`.`ward_desc`, `a`.`sszyresult`, `a`.`lastupdatedttm`, `a`.`rowkey`
FROM (SELECT 'HID0101' AS `hosp_code`, `hid0101_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0101_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0101_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0101_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0101_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc`, CAST((count(DISTINCT `hid0101_cache_his_dhcapp_sqluser`.`a`.`paadm_admno`)) AS INT) AS `sszyresult`, current_timestamp() AS `lastupdatedttm`, concat('HID0101_2_', CAST((current_timestamp()) AS VARCHAR), `hid0101_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`) AS `rowkey`
FROM `hid0101_cache_his_dhcapp_sqluser`.`pa_adm` AS `a` LEFT OUTER JOIN `hid0101_cache_his_dhcapp_sqluser`.`ct_loc` AS `b` ON `hid0101_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr` = `hid0101_cache_his_dhcapp_sqluser`.`b`.`ctloc_rowid` LEFT OUTER JOIN `hid0101_cache_his_dhcapp_sqluser`.`pac_ward` AS `pac_ward` ON `hid0101_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_rowid` = `hid0101_cache_his_dhcapp_sqluser`.`a`.`paadm_currentward_dr`
WHERE ((`hid0101_cache_his_dhcapp_sqluser`.`a`.`paadm_rowid` NOT IN (((((SELECT `indicators`.`tmp_exclude_ids`.`id`
FROM `indicators`.`tmp_exclude_ids`)))))) AND ((`hid0101_cache_his_dhcapp_sqluser`.`a`.`paadm_type` = 'I') AND (`hid0101_cache_his_dhcapp_sqluser`.`a`.`paadm_visitstatus` = 'A'))) AND (`hid0101_cache_his_dhcapp_sqluser`.`a`.`paadm_currentbed_dr` IS NOT NULL)
GROUP BY `hid0101_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0101_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0101_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0101_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0101_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc` UNION ALL SELECT 'HID0103' AS `hosp_code`, `hid0103_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0103_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0103_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0103_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0103_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc`, CAST((count(DISTINCT `hid0103_cache_his_dhcapp_sqluser`.`a`.`paadm_admno`)) AS INT) AS `sszyresult`, current_timestamp() AS `lastupdatedttm`, concat('HID0103_2_', CAST((current_timestamp()) AS VARCHAR), `hid0103_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`) AS `rowkey`
FROM `hid0103_cache_his_dhcapp_sqluser`.`pa_adm` AS `a` LEFT OUTER JOIN `hid0103_cache_his_dhcapp_sqluser`.`ct_loc` AS `b` ON `hid0103_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr` = `hid0103_cache_his_dhcapp_sqluser`.`b`.`ctloc_rowid` LEFT OUTER JOIN `hid0103_cache_his_dhcapp_sqluser`.`pac_ward` AS `pac_ward` ON `hid0103_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_rowid` = `hid0103_cache_his_dhcapp_sqluser`.`a`.`paadm_currentward_dr`
WHERE ((`hid0103_cache_his_dhcapp_sqluser`.`a`.`paadm_type` = 'I') AND (`hid0103_cache_his_dhcapp_sqluser`.`a`.`paadm_visitstatus` = 'A')) AND (`hid0103_cache_his_dhcapp_sqluser`.`a`.`paadm_currentbed_dr` IS NOT NULL)
GROUP BY `hid0103_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0103_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0103_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0103_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0103_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc` UNION ALL SELECT 'HID0117' AS `hosp_code`, `hid0117_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0117_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0117_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0117_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0117_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc`, CAST((count(DISTINCT `hid0117_cache_his_dhcapp_sqluser`.`a`.`paadm_admno`)) AS INT) AS `sszyresult`, current_timestamp() AS `lastupdatedttm`, concat('HID0117_1_', CAST((current_timestamp()) AS VARCHAR), `hid0117_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`) AS `rowkey`
FROM `hid0117_cache_his_dhcapp_sqluser`.`pa_adm` AS `a` LEFT OUTER JOIN `hid0117_cache_his_dhcapp_sqluser`.`ct_loc` AS `b` ON `hid0117_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr` = `hid0117_cache_his_dhcapp_sqluser`.`b`.`ctloc_rowid` LEFT OUTER JOIN `hid0117_cache_his_dhcapp_sqluser`.`pac_ward` AS `pac_ward` ON `hid0117_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_rowid` = `hid0117_cache_his_dhcapp_sqluser`.`a`.`paadm_currentward_dr`
WHERE ((`hid0117_cache_his_dhcapp_sqluser`.`a`.`paadm_type` = 'I') AND (`hid0117_cache_his_dhcapp_sqluser`.`a`.`paadm_visitstatus` = 'A')) AND (`hid0117_cache_his_dhcapp_sqluser`.`a`.`paadm_currentbed_dr` IS NOT NULL)
GROUP BY `hid0117_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0117_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0117_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0117_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0117_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc`) `a`
WHERE NOT (`a`.`ctloc_desc` LIKE '%测试%') UNION ALL SELECT 'HID0120' AS `hosp_code`, `hid0120_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0120_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0120_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0120_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0120_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc`, CAST((count(DISTINCT `hid0120_cache_his_dhcapp_sqluser`.`a`.`paadm_admno`)) AS INT) AS `sszyresult`, current_timestamp() AS `lastupdatedttm`, concat('HID0120_2_', CAST((current_timestamp()) AS VARCHAR), `hid0120_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`) AS `rowkey`
FROM `hid0120_cache_his_dhcapp_sqluser`.`pa_adm` AS `a` LEFT OUTER JOIN `hid0120_cache_his_dhcapp_sqluser`.`ct_loc` AS `b` ON `hid0120_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr` = `hid0120_cache_his_dhcapp_sqluser`.`b`.`ctloc_rowid` LEFT OUTER JOIN `hid0120_cache_his_dhcapp_sqluser`.`pac_ward` AS `pac_ward` ON `hid0120_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_rowid` = `hid0120_cache_his_dhcapp_sqluser`.`a`.`paadm_currentward_dr`
WHERE ((`hid0120_cache_his_dhcapp_sqluser`.`a`.`paadm_type` = 'I') AND (`hid0120_cache_his_dhcapp_sqluser`.`a`.`paadm_visitstatus` = 'A')) AND (`hid0120_cache_his_dhcapp_sqluser`.`a`.`paadm_currentbed_dr` IS NOT NULL)
GROUP BY `hid0120_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0120_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0120_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0120_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0120_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc` UNION ALL SELECT 'HID0122' AS `hosp_code`, `hid0122_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0122_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0122_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0122_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0122_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc`, CAST((count(DISTINCT `hid0122_cache_his_dhcapp_sqluser`.`a`.`paadm_admno`)) AS INT) AS `sszyresult`, current_timestamp() AS `lastupdatedttm`, concat('HID0122_2_', CAST((current_timestamp()) AS VARCHAR), `hid0122_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`) AS `rowkey`
FROM `hid0122_cache_his_dhcapp_sqluser`.`pa_adm` AS `a` LEFT OUTER JOIN `hid0122_cache_his_dhcapp_sqluser`.`ct_loc` AS `b` ON `hid0122_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr` = `hid0122_cache_his_dhcapp_sqluser`.`b`.`ctloc_rowid` LEFT OUTER JOIN `hid0122_cache_his_dhcapp_sqluser`.`pac_ward` AS `pac_ward` ON `hid0122_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_rowid` = `hid0122_cache_his_dhcapp_sqluser`.`a`.`paadm_currentward_dr`
WHERE ((`hid0122_cache_his_dhcapp_sqluser`.`a`.`paadm_type` = 'I') AND (`hid0122_cache_his_dhcapp_sqluser`.`a`.`paadm_visitstatus` = 'A')) AND (`hid0122_cache_his_dhcapp_sqluser`.`a`.`paadm_currentbed_dr` IS NOT NULL)
GROUP BY `hid0122_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0122_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0122_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0122_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0122_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc` UNION ALL SELECT 'HID0123' AS `hosp_code`, `hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0123_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0123_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc`, CAST((count(DISTINCT `hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_admno`)) AS INT) AS `sszyresult`, current_timestamp() AS `lastupdatedttm`, concat('HID0123_2_', CAST((current_timestamp()) AS VARCHAR), `hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`) AS `rowkey`
FROM `hid0123_cache_his_dhcapp_sqluser`.`pa_adm` AS `a` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`ct_loc` AS `b` ON `hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr` = `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_rowid` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`pac_ward` AS `pac_ward` ON `hid0123_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_rowid` = `hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_currentward_dr`
WHERE ((`hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_type` = 'I') AND (`hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_visitstatus` = 'A')) AND (`hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_currentbed_dr` IS NOT NULL) AND (`hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_hospital_dr` = '2')
GROUP BY `hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0123_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0123_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc` UNION ALL SELECT 'HID0124' AS `hosp_code`, `hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0123_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0123_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc`, CAST((count(DISTINCT `hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_admno`)) AS INT) AS `sszyresult`, current_timestamp() AS `lastupdatedttm`, concat('HID0124_2_', CAST((current_timestamp()) AS VARCHAR), `hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`) AS `rowkey`
FROM `hid0123_cache_his_dhcapp_sqluser`.`pa_adm` AS `a` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`ct_loc` AS `b` ON `hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr` = `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_rowid` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`pac_ward` AS `pac_ward` ON `hid0123_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_rowid` = `hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_currentward_dr`
WHERE ((`hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_type` = 'I') AND (`hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_visitstatus` = 'A')) AND (`hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_currentbed_dr` IS NOT NULL) AND (`hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_hospital_dr` = '12')
GROUP BY `hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0123_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0123_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc`;
