-- mzssxz_indicators_v3 全量建表（含 HID0123/HID0124）
-- 院区：HID0101/0103/0117/0120/0122/0123/0124
-- hid0123 库两院区：ct_loc.ctloc_hospital_dr 2→HID0123，12→HID0124
-- 已有 MV 需 DROP 后重建，异步 MV 不支持直接改 AS 定义

CREATE MATERIALIZED VIEW `indicators`.`mzssxz_indicators_v3` (`hosp_code`, `ctloc_desc`, `ctloc_code`, `questatedr`, `paadm_type`, `ghl`, `lastupdatedttm`)
COMMENT "实时就诊挂号"
DISTRIBUTED BY HASH(`hosp_code`)
REFRESH ASYNC EVERY(INTERVAL 180 SECOND)
PROPERTIES (
"replicated_storage" = "true",
"replication_num" = "3",
"storage_medium" = "HDD"
)
AS SELECT 'HID0101' AS `hosp_code`, `hid0101_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0101_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0101_cache_his_dhcapp_sqluser`.`a`.`questatedr`, `hid0101_cache_his_dhcapp_sqluser`.`adm`.`paadm_type`, count(1) AS `ghl`, current_timestamp() AS `lastupdatedttm`
FROM `hid0101_cache_his_dhcapp_sqluser`.`dhcqueue` AS `a` LEFT OUTER JOIN `hid0101_cache_his_dhcapp_sqluser`.`ct_loc` AS `b` ON `hid0101_cache_his_dhcapp_sqluser`.`a`.`quedepdr` = `hid0101_cache_his_dhcapp_sqluser`.`b`.`ctloc_rowid` LEFT OUTER JOIN `hid0101_cache_his_dhcapp_sqluser`.`pa_adm` AS `adm` ON `hid0101_cache_his_dhcapp_sqluser`.`adm`.`paadm_rowid` = `hid0101_cache_his_dhcapp_sqluser`.`a`.`quepaadmdr`
WHERE (((((CAST(`hid0101_cache_his_dhcapp_sqluser`.`a`.`quedate` AS VARCHAR)) = (substring(CAST((current_timestamp()) AS VARCHAR), 1, 10))) AND (`hid0101_cache_his_dhcapp_sqluser`.`a`.`questatedr` IN ('1', '2', '3', '4', '6', '7'))) AND (`hid0101_cache_his_dhcapp_sqluser`.`a`.`queno` != '')) AND (NOT (`hid0101_cache_his_dhcapp_sqluser`.`a`.`queno` LIKE '%慢%'))) AND ((CAST(`hid0101_cache_his_dhcapp_sqluser`.`adm`.`paadm_admdate` AS VARCHAR)) = (substring(CAST((current_timestamp()) AS VARCHAR), 1, 10)))
GROUP BY `hid0101_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0101_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0101_cache_his_dhcapp_sqluser`.`a`.`questatedr`, `hid0101_cache_his_dhcapp_sqluser`.`adm`.`paadm_type` UNION ALL SELECT 'HID0103' AS `hosp_code`, `hid0103_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0103_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0103_cache_his_dhcapp_sqluser`.`a`.`questatedr`, `hid0103_cache_his_dhcapp_sqluser`.`adm`.`paadm_type`, count(1) AS `ghl`, current_timestamp() AS `lastupdatedttm`
FROM `hid0103_cache_his_dhcapp_sqluser`.`dhcqueue` AS `a` LEFT OUTER JOIN `hid0103_cache_his_dhcapp_sqluser`.`ct_loc` AS `b` ON `hid0103_cache_his_dhcapp_sqluser`.`a`.`quedepdr` = `hid0103_cache_his_dhcapp_sqluser`.`b`.`ctloc_rowid` LEFT OUTER JOIN `hid0103_cache_his_dhcapp_sqluser`.`pa_adm` AS `adm` ON `hid0103_cache_his_dhcapp_sqluser`.`adm`.`paadm_rowid` = `hid0103_cache_his_dhcapp_sqluser`.`a`.`quepaadmdr`
WHERE (((((CAST(`hid0103_cache_his_dhcapp_sqluser`.`a`.`quedate` AS VARCHAR)) = (substring(CAST((current_timestamp()) AS VARCHAR), 1, 10))) AND (`hid0103_cache_his_dhcapp_sqluser`.`a`.`questatedr` IN ('1', '2', '3', '4', '6', '7'))) AND (`hid0103_cache_his_dhcapp_sqluser`.`a`.`queno` != '')) AND (NOT (`hid0103_cache_his_dhcapp_sqluser`.`a`.`queno` LIKE '%慢%'))) AND ((CAST(`hid0103_cache_his_dhcapp_sqluser`.`adm`.`paadm_admdate` AS VARCHAR)) = (substring(CAST((current_timestamp()) AS VARCHAR), 1, 10)))
GROUP BY `hid0103_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0103_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0103_cache_his_dhcapp_sqluser`.`a`.`questatedr`, `hid0103_cache_his_dhcapp_sqluser`.`adm`.`paadm_type` UNION ALL SELECT 'HID0117' AS `hosp_code`, `hid0117_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0117_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0117_cache_his_dhcapp_sqluser`.`a`.`questatedr`, `hid0117_cache_his_dhcapp_sqluser`.`adm`.`paadm_type`, count(1) AS `ghl`, current_timestamp() AS `lastupdatedttm`
FROM `hid0117_cache_his_dhcapp_sqluser`.`dhcqueue` AS `a` LEFT OUTER JOIN `hid0117_cache_his_dhcapp_sqluser`.`ct_loc` AS `b` ON `hid0117_cache_his_dhcapp_sqluser`.`a`.`quedepdr` = `hid0117_cache_his_dhcapp_sqluser`.`b`.`ctloc_rowid` LEFT OUTER JOIN `hid0117_cache_his_dhcapp_sqluser`.`pa_adm` AS `adm` ON `hid0117_cache_his_dhcapp_sqluser`.`adm`.`paadm_rowid` = `hid0117_cache_his_dhcapp_sqluser`.`a`.`quepaadmdr`
WHERE (((((CAST(`hid0117_cache_his_dhcapp_sqluser`.`a`.`quedate` AS VARCHAR)) = (substring(CAST((current_timestamp()) AS VARCHAR), 1, 10))) AND (`hid0117_cache_his_dhcapp_sqluser`.`a`.`questatedr` IN ('1', '2', '3', '4', '6', '7'))) AND (`hid0117_cache_his_dhcapp_sqluser`.`a`.`queno` != '')) AND (NOT (`hid0117_cache_his_dhcapp_sqluser`.`a`.`queno` LIKE '%慢%'))) AND ((CAST(`hid0117_cache_his_dhcapp_sqluser`.`adm`.`paadm_admdate` AS VARCHAR)) = (substring(CAST((current_timestamp()) AS VARCHAR), 1, 10)))
GROUP BY `hid0117_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0117_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0117_cache_his_dhcapp_sqluser`.`a`.`questatedr`, `hid0117_cache_his_dhcapp_sqluser`.`adm`.`paadm_type` UNION ALL SELECT 'HID0120' AS `hosp_code`, `hid0120_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0120_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0120_cache_his_dhcapp_sqluser`.`a`.`questatedr`, `hid0120_cache_his_dhcapp_sqluser`.`adm`.`paadm_type`, count(1) AS `ghl`, current_timestamp() AS `lastupdatedttm`
FROM `hid0120_cache_his_dhcapp_sqluser`.`dhcqueue` AS `a` LEFT OUTER JOIN `hid0120_cache_his_dhcapp_sqluser`.`ct_loc` AS `b` ON `hid0120_cache_his_dhcapp_sqluser`.`a`.`quedepdr` = `hid0120_cache_his_dhcapp_sqluser`.`b`.`ctloc_rowid` LEFT OUTER JOIN `hid0120_cache_his_dhcapp_sqluser`.`pa_adm` AS `adm` ON `hid0120_cache_his_dhcapp_sqluser`.`adm`.`paadm_rowid` = `hid0120_cache_his_dhcapp_sqluser`.`a`.`quepaadmdr`
WHERE (((((CAST(`hid0120_cache_his_dhcapp_sqluser`.`a`.`quedate` AS VARCHAR)) = (substring(CAST((current_timestamp()) AS VARCHAR), 1, 10))) AND (`hid0120_cache_his_dhcapp_sqluser`.`a`.`questatedr` IN ('1', '2', '3', '4', '6', '7'))) AND (`hid0120_cache_his_dhcapp_sqluser`.`a`.`queno` != '')) AND (NOT (`hid0120_cache_his_dhcapp_sqluser`.`a`.`queno` LIKE '%慢%'))) AND ((CAST(`hid0120_cache_his_dhcapp_sqluser`.`adm`.`paadm_admdate` AS VARCHAR)) = (substring(CAST((current_timestamp()) AS VARCHAR), 1, 10)))
GROUP BY `hid0120_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0120_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0120_cache_his_dhcapp_sqluser`.`a`.`questatedr`, `hid0120_cache_his_dhcapp_sqluser`.`adm`.`paadm_type` UNION ALL SELECT 'HID0122' AS `hosp_code`, `hid0122_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0122_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0122_cache_his_dhcapp_sqluser`.`a`.`questatedr`, `hid0122_cache_his_dhcapp_sqluser`.`adm`.`paadm_type`, count(1) AS `ghl`, current_timestamp() AS `lastupdatedttm`
FROM `hid0122_cache_his_dhcapp_sqluser`.`dhcqueue` AS `a` LEFT OUTER JOIN `hid0122_cache_his_dhcapp_sqluser`.`ct_loc` AS `b` ON `hid0122_cache_his_dhcapp_sqluser`.`a`.`quedepdr` = `hid0122_cache_his_dhcapp_sqluser`.`b`.`ctloc_rowid` LEFT OUTER JOIN `hid0122_cache_his_dhcapp_sqluser`.`pa_adm` AS `adm` ON `hid0122_cache_his_dhcapp_sqluser`.`adm`.`paadm_rowid` = `hid0122_cache_his_dhcapp_sqluser`.`a`.`quepaadmdr`
WHERE (((((CAST(`hid0122_cache_his_dhcapp_sqluser`.`a`.`quedate` AS VARCHAR)) = (substring(CAST((current_timestamp()) AS VARCHAR), 1, 10))) AND (`hid0122_cache_his_dhcapp_sqluser`.`a`.`questatedr` IN ('1', '2', '3', '4', '6', '7'))) AND (`hid0122_cache_his_dhcapp_sqluser`.`a`.`queno` != '')) AND (NOT (`hid0122_cache_his_dhcapp_sqluser`.`a`.`queno` LIKE '%慢%'))) AND ((CAST(`hid0122_cache_his_dhcapp_sqluser`.`adm`.`paadm_admdate` AS VARCHAR)) = (substring(CAST((current_timestamp()) AS VARCHAR), 1, 10)))
GROUP BY `hid0122_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0122_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0122_cache_his_dhcapp_sqluser`.`a`.`questatedr`, `hid0122_cache_his_dhcapp_sqluser`.`adm`.`paadm_type` UNION ALL SELECT 'HID0123' AS `hosp_code`, `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0123_cache_his_dhcapp_sqluser`.`a`.`questatedr`, `hid0123_cache_his_dhcapp_sqluser`.`adm`.`paadm_type`, count(1) AS `ghl`, current_timestamp() AS `lastupdatedttm`
FROM `hid0123_cache_his_dhcapp_sqluser`.`dhcqueue` AS `a` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`ct_loc` AS `b` ON `hid0123_cache_his_dhcapp_sqluser`.`a`.`quedepdr` = `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_rowid` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`pa_adm` AS `adm` ON `hid0123_cache_his_dhcapp_sqluser`.`adm`.`paadm_rowid` = `hid0123_cache_his_dhcapp_sqluser`.`a`.`quepaadmdr`
WHERE (((((CAST(`hid0123_cache_his_dhcapp_sqluser`.`a`.`quedate` AS VARCHAR)) = (substring(CAST((current_timestamp()) AS VARCHAR), 1, 10))) AND (`hid0123_cache_his_dhcapp_sqluser`.`a`.`questatedr` IN ('1', '2', '3', '4', '6', '7'))) AND (`hid0123_cache_his_dhcapp_sqluser`.`a`.`queno` != '')) AND (NOT (`hid0123_cache_his_dhcapp_sqluser`.`a`.`queno` LIKE '%慢%'))) AND ((CAST(`hid0123_cache_his_dhcapp_sqluser`.`adm`.`paadm_admdate` AS VARCHAR)) = (substring(CAST((current_timestamp()) AS VARCHAR), 1, 10))) AND (`hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_hospital_dr` = '2')
GROUP BY `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0123_cache_his_dhcapp_sqluser`.`a`.`questatedr`, `hid0123_cache_his_dhcapp_sqluser`.`adm`.`paadm_type` UNION ALL SELECT 'HID0124' AS `hosp_code`, `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0123_cache_his_dhcapp_sqluser`.`a`.`questatedr`, `hid0123_cache_his_dhcapp_sqluser`.`adm`.`paadm_type`, count(1) AS `ghl`, current_timestamp() AS `lastupdatedttm`
FROM `hid0123_cache_his_dhcapp_sqluser`.`dhcqueue` AS `a` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`ct_loc` AS `b` ON `hid0123_cache_his_dhcapp_sqluser`.`a`.`quedepdr` = `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_rowid` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`pa_adm` AS `adm` ON `hid0123_cache_his_dhcapp_sqluser`.`adm`.`paadm_rowid` = `hid0123_cache_his_dhcapp_sqluser`.`a`.`quepaadmdr`
WHERE (((((CAST(`hid0123_cache_his_dhcapp_sqluser`.`a`.`quedate` AS VARCHAR)) = (substring(CAST((current_timestamp()) AS VARCHAR), 1, 10))) AND (`hid0123_cache_his_dhcapp_sqluser`.`a`.`questatedr` IN ('1', '2', '3', '4', '6', '7'))) AND (`hid0123_cache_his_dhcapp_sqluser`.`a`.`queno` != '')) AND (NOT (`hid0123_cache_his_dhcapp_sqluser`.`a`.`queno` LIKE '%慢%'))) AND ((CAST(`hid0123_cache_his_dhcapp_sqluser`.`adm`.`paadm_admdate` AS VARCHAR)) = (substring(CAST((current_timestamp()) AS VARCHAR), 1, 10))) AND (`hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_hospital_dr` = '12')
GROUP BY `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0123_cache_his_dhcapp_sqluser`.`a`.`questatedr`, `hid0123_cache_his_dhcapp_sqluser`.`adm`.`paadm_type`;
