-- StarRocks 物化视图：库 indicators；7 院区 UNION（HID0101/0103/0117/0120 + 公卫 HID0122/HID0123/HID0124）
-- 实时指标 5 个后缀 _v3；医技/放射 3 个仍为 _v2
-- fsjcl_v2 仅本部 hid0101_mssql RIS/超声，公卫无同源库未并入

CREATE MATERIALIZED VIEW `indicators`.`currentcyxz_v3` (`hosp_code`, `paadm_depcode_dr`, `ctloc_code`, `ctloc_desc`, `ward_code`, `ward_desc`, `sscyresult`, `lastupdatedttm`)
COMMENT "实时出院人次汇总"
DISTRIBUTED BY HASH(`hosp_code`)
REFRESH ASYNC EVERY(INTERVAL 180 SECOND)
PROPERTIES (
"replicated_storage" = "true",
"replication_num" = "3",
"storage_medium" = "HDD"
)
AS SELECT 'HID0101' AS `hosp_code`, `hid0101_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0101_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0101_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0101_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0101_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc`, count(DISTINCT `hid0101_cache_his_dhcapp_sqluser`.`a`.`paadm_admno`) AS `sscyresult`, current_timestamp() AS `lastupdatedttm`
FROM `hid0101_cache_his_dhcapp_sqluser`.`pa_adm` AS `a` LEFT OUTER JOIN `hid0101_cache_his_dhcapp_sqluser`.`ct_loc` AS `b` ON `hid0101_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr` = `hid0101_cache_his_dhcapp_sqluser`.`b`.`ctloc_rowid` LEFT OUTER JOIN `hid0101_cache_his_dhcapp_sqluser`.`pac_ward` AS `pac_ward` ON `hid0101_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_rowid` = `hid0101_cache_his_dhcapp_sqluser`.`a`.`paadm_currentward_dr`
WHERE ((`hid0101_cache_his_dhcapp_sqluser`.`a`.`paadm_rowid` NOT IN (((((SELECT `indicators`.`tmp_exclude_ids`.`id`
FROM `indicators`.`tmp_exclude_ids`)))))) AND (((`hid0101_cache_his_dhcapp_sqluser`.`a`.`paadm_type` = 'I') AND (`hid0101_cache_his_dhcapp_sqluser`.`a`.`paadm_visitstatus` != 'C')) AND (`hid0101_cache_his_dhcapp_sqluser`.`a`.`paadm_dischgdate` IS NOT NULL))) AND ((CAST(`hid0101_cache_his_dhcapp_sqluser`.`a`.`paadm_dischgdate` AS VARCHAR)) = (substring(CAST((current_timestamp()) AS VARCHAR), 1, 10)))
GROUP BY `hid0101_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0101_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0101_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0101_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0101_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc` UNION ALL SELECT 'HID0103' AS `hosp_code`, `hid0103_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0103_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0103_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0103_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0103_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc`, count(DISTINCT `hid0103_cache_his_dhcapp_sqluser`.`a`.`paadm_admno`) AS `sscyresult`, current_timestamp() AS `lastupdatedttm`
FROM `hid0103_cache_his_dhcapp_sqluser`.`pa_adm` AS `a` LEFT OUTER JOIN `hid0103_cache_his_dhcapp_sqluser`.`ct_loc` AS `b` ON `hid0103_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr` = `hid0103_cache_his_dhcapp_sqluser`.`b`.`ctloc_rowid` LEFT OUTER JOIN `hid0103_cache_his_dhcapp_sqluser`.`pac_ward` AS `pac_ward` ON `hid0103_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_rowid` = `hid0103_cache_his_dhcapp_sqluser`.`a`.`paadm_currentward_dr`
WHERE (((`hid0103_cache_his_dhcapp_sqluser`.`a`.`paadm_type` = 'I') AND (`hid0103_cache_his_dhcapp_sqluser`.`a`.`paadm_visitstatus` != 'C')) AND (`hid0103_cache_his_dhcapp_sqluser`.`a`.`paadm_dischgdate` IS NOT NULL)) AND ((CAST(`hid0103_cache_his_dhcapp_sqluser`.`a`.`paadm_dischgdate` AS VARCHAR)) = (substring(CAST((current_timestamp()) AS VARCHAR), 1, 10)))
GROUP BY `hid0103_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0103_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0103_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0103_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0103_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc` UNION ALL SELECT 'HID0117' AS `hosp_code`, `hid0117_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0117_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0117_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0117_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0117_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc`, count(DISTINCT `hid0117_cache_his_dhcapp_sqluser`.`a`.`paadm_admno`) AS `sscyresult`, current_timestamp() AS `lastupdatedttm`
FROM `hid0117_cache_his_dhcapp_sqluser`.`pa_adm` AS `a` LEFT OUTER JOIN `hid0117_cache_his_dhcapp_sqluser`.`ct_loc` AS `b` ON `hid0117_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr` = `hid0117_cache_his_dhcapp_sqluser`.`b`.`ctloc_rowid` LEFT OUTER JOIN `hid0117_cache_his_dhcapp_sqluser`.`pac_ward` AS `pac_ward` ON `hid0117_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_rowid` = `hid0117_cache_his_dhcapp_sqluser`.`a`.`paadm_currentward_dr`
WHERE (((`hid0117_cache_his_dhcapp_sqluser`.`a`.`paadm_type` = 'I') AND (`hid0117_cache_his_dhcapp_sqluser`.`a`.`paadm_visitstatus` != 'C')) AND (`hid0117_cache_his_dhcapp_sqluser`.`a`.`paadm_dischgdate` IS NOT NULL)) AND ((CAST(`hid0117_cache_his_dhcapp_sqluser`.`a`.`paadm_dischgdate` AS VARCHAR)) = (substring(CAST((current_timestamp()) AS VARCHAR), 1, 10)))
GROUP BY `hid0117_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0117_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0117_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0117_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0117_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc` UNION ALL SELECT 'HID0120' AS `hosp_code`, `hid0120_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0120_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0120_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0120_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0120_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc`, count(DISTINCT `hid0120_cache_his_dhcapp_sqluser`.`a`.`paadm_admno`) AS `sscyresult`, current_timestamp() AS `lastupdatedttm`
FROM `hid0120_cache_his_dhcapp_sqluser`.`pa_adm` AS `a` LEFT OUTER JOIN `hid0120_cache_his_dhcapp_sqluser`.`ct_loc` AS `b` ON `hid0120_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr` = `hid0120_cache_his_dhcapp_sqluser`.`b`.`ctloc_rowid` LEFT OUTER JOIN `hid0120_cache_his_dhcapp_sqluser`.`pac_ward` AS `pac_ward` ON `hid0120_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_rowid` = `hid0120_cache_his_dhcapp_sqluser`.`a`.`paadm_currentward_dr`
WHERE (((`hid0120_cache_his_dhcapp_sqluser`.`a`.`paadm_type` = 'I') AND (`hid0120_cache_his_dhcapp_sqluser`.`a`.`paadm_visitstatus` != 'C')) AND (`hid0120_cache_his_dhcapp_sqluser`.`a`.`paadm_dischgdate` IS NOT NULL)) AND ((CAST(`hid0120_cache_his_dhcapp_sqluser`.`a`.`paadm_dischgdate` AS VARCHAR)) = (substring(CAST((current_timestamp()) AS VARCHAR), 1, 10)))
GROUP BY `hid0120_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0120_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0120_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0120_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0120_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc` UNION ALL SELECT 'HID0122' AS `hosp_code`, `hid0122_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0122_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0122_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0122_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0122_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc`, count(DISTINCT `hid0122_cache_his_dhcapp_sqluser`.`a`.`paadm_admno`) AS `sscyresult`, current_timestamp() AS `lastupdatedttm`
FROM `hid0122_cache_his_dhcapp_sqluser`.`pa_adm` AS `a` LEFT OUTER JOIN `hid0122_cache_his_dhcapp_sqluser`.`ct_loc` AS `b` ON `hid0122_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr` = `hid0122_cache_his_dhcapp_sqluser`.`b`.`ctloc_rowid` LEFT OUTER JOIN `hid0122_cache_his_dhcapp_sqluser`.`pac_ward` AS `pac_ward` ON `hid0122_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_rowid` = `hid0122_cache_his_dhcapp_sqluser`.`a`.`paadm_currentward_dr`
WHERE (((`hid0122_cache_his_dhcapp_sqluser`.`a`.`paadm_type` = 'I') AND (`hid0122_cache_his_dhcapp_sqluser`.`a`.`paadm_visitstatus` != 'C')) AND (`hid0122_cache_his_dhcapp_sqluser`.`a`.`paadm_dischgdate` IS NOT NULL)) AND ((CAST(`hid0122_cache_his_dhcapp_sqluser`.`a`.`paadm_dischgdate` AS VARCHAR)) = (substring(CAST((current_timestamp()) AS VARCHAR), 1, 10)))
GROUP BY `hid0122_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0122_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0122_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0122_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0122_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc` UNION ALL SELECT 'HID0123' AS `hosp_code`, `hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0123_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0123_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc`, count(DISTINCT `hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_admno`) AS `sscyresult`, current_timestamp() AS `lastupdatedttm`
FROM `hid0123_cache_his_dhcapp_sqluser`.`pa_adm` AS `a` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`ct_loc` AS `b` ON `hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr` = `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_rowid` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`pac_ward` AS `pac_ward` ON `hid0123_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_rowid` = `hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_currentward_dr`
WHERE ((((`hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_type` = 'I') AND (`hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_visitstatus` != 'C')) AND (`hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_dischgdate` IS NOT NULL)) AND ((CAST(`hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_dischgdate` AS VARCHAR)) = (substring(CAST((current_timestamp()) AS VARCHAR), 1, 10)))) AND (`hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_hospital_dr` = '2')
GROUP BY `hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0123_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0123_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc` UNION ALL SELECT 'HID0124' AS `hosp_code`, `hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0123_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0123_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc`, count(DISTINCT `hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_admno`) AS `sscyresult`, current_timestamp() AS `lastupdatedttm`
FROM `hid0123_cache_his_dhcapp_sqluser`.`pa_adm` AS `a` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`ct_loc` AS `b` ON `hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr` = `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_rowid` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`pac_ward` AS `pac_ward` ON `hid0123_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_rowid` = `hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_currentward_dr`
WHERE ((((`hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_type` = 'I') AND (`hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_visitstatus` != 'C')) AND (`hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_dischgdate` IS NOT NULL)) AND ((CAST(`hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_dischgdate` AS VARCHAR)) = (substring(CAST((current_timestamp()) AS VARCHAR), 1, 10)))) AND (`hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_hospital_dr` = '12')
GROUP BY `hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0123_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0123_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc`;

CREATE MATERIALIZED VIEW `indicators`.`currentryxz_v3` (`hosp_code`, `paadm_depcode_dr`, `ctloc_code`, `ctloc_desc`, `ward_code`, `ward_desc`, `ssryresult`, `lastupdatedttm`)
COMMENT "实时入院人次"
DISTRIBUTED BY HASH(`hosp_code`)
REFRESH ASYNC EVERY(INTERVAL 180 SECOND)
PROPERTIES (
"replicated_storage" = "true",
"replication_num" = "3",
"storage_medium" = "HDD"
)
AS SELECT 'HID0101' AS `hosp_code`, `hid0101_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0101_cache_his_dhcapp_sqluser`.`c`.`ctloc_code`, `hid0101_cache_his_dhcapp_sqluser`.`c`.`ctloc_desc`, `hid0101_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0101_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc`, count(DISTINCT `hid0101_cache_his_dhcapp_sqluser`.`a`.`paadm_admno`) AS `ssryresult`, current_timestamp() AS `lastupdatedttm`
FROM `hid0101_cache_his_dhcapp_sqluser`.`pa_adm` AS `a` LEFT OUTER JOIN `hid0101_cache_his_dhcapp_sqluser`.`ct_loc` AS `c` ON `hid0101_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr` = `hid0101_cache_his_dhcapp_sqluser`.`c`.`ctloc_rowid` LEFT OUTER JOIN `hid0101_cache_his_dhcapp_sqluser`.`pac_ward` AS `pac_ward` ON `hid0101_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_rowid` = `hid0101_cache_his_dhcapp_sqluser`.`a`.`paadm_currentward_dr`
WHERE ((`hid0101_cache_his_dhcapp_sqluser`.`a`.`paadm_rowid` NOT IN (((((SELECT `indicators`.`tmp_exclude_ids`.`id`
FROM `indicators`.`tmp_exclude_ids`)))))) AND ((((CAST(`hid0101_cache_his_dhcapp_sqluser`.`a`.`paadm_admdate` AS VARCHAR)) = (substring(CAST((current_timestamp()) AS VARCHAR), 1, 10))) AND (`hid0101_cache_his_dhcapp_sqluser`.`a`.`paadm_type` = 'I')) AND (`hid0101_cache_his_dhcapp_sqluser`.`a`.`paadm_visitstatus` != 'C'))) AND (`hid0101_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr` IS NOT NULL)
GROUP BY `hid0101_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0101_cache_his_dhcapp_sqluser`.`c`.`ctloc_code`, `hid0101_cache_his_dhcapp_sqluser`.`c`.`ctloc_desc`, `hid0101_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0101_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc` UNION ALL SELECT 'HID0103' AS `hosp_code`, `hid0103_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0103_cache_his_dhcapp_sqluser`.`c`.`ctloc_code`, `hid0103_cache_his_dhcapp_sqluser`.`c`.`ctloc_desc`, `hid0103_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0103_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc`, count(DISTINCT `hid0103_cache_his_dhcapp_sqluser`.`a`.`paadm_admno`) AS `ssryresult`, current_timestamp() AS `lastupdatedttm`
FROM `hid0103_cache_his_dhcapp_sqluser`.`pa_adm` AS `a` LEFT OUTER JOIN `hid0103_cache_his_dhcapp_sqluser`.`ct_loc` AS `c` ON `hid0103_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr` = `hid0103_cache_his_dhcapp_sqluser`.`c`.`ctloc_rowid` LEFT OUTER JOIN `hid0103_cache_his_dhcapp_sqluser`.`pac_ward` AS `pac_ward` ON `hid0103_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_rowid` = `hid0103_cache_his_dhcapp_sqluser`.`a`.`paadm_currentward_dr`
WHERE ((((CAST(`hid0103_cache_his_dhcapp_sqluser`.`a`.`paadm_admdate` AS VARCHAR)) = (substring(CAST((current_timestamp()) AS VARCHAR), 1, 10))) AND (`hid0103_cache_his_dhcapp_sqluser`.`a`.`paadm_type` = 'I')) AND (`hid0103_cache_his_dhcapp_sqluser`.`a`.`paadm_visitstatus` != 'C')) AND (`hid0103_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr` IS NOT NULL)
GROUP BY `hid0103_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0103_cache_his_dhcapp_sqluser`.`c`.`ctloc_code`, `hid0103_cache_his_dhcapp_sqluser`.`c`.`ctloc_desc`, `hid0103_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0103_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc` UNION ALL SELECT 'HID0117' AS `hosp_code`, `hid0117_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0117_cache_his_dhcapp_sqluser`.`c`.`ctloc_code`, `hid0117_cache_his_dhcapp_sqluser`.`c`.`ctloc_desc`, `hid0117_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0117_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc`, count(DISTINCT `hid0117_cache_his_dhcapp_sqluser`.`a`.`paadm_admno`) AS `ssryresult`, current_timestamp() AS `lastupdatedttm`
FROM `hid0117_cache_his_dhcapp_sqluser`.`pa_adm` AS `a` LEFT OUTER JOIN `hid0117_cache_his_dhcapp_sqluser`.`ct_loc` AS `c` ON `hid0117_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr` = `hid0117_cache_his_dhcapp_sqluser`.`c`.`ctloc_rowid` LEFT OUTER JOIN `hid0117_cache_his_dhcapp_sqluser`.`pac_ward` AS `pac_ward` ON `hid0117_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_rowid` = `hid0117_cache_his_dhcapp_sqluser`.`a`.`paadm_currentward_dr`
WHERE ((((CAST(`hid0117_cache_his_dhcapp_sqluser`.`a`.`paadm_admdate` AS VARCHAR)) = (substring(CAST((current_timestamp()) AS VARCHAR), 1, 10))) AND (`hid0117_cache_his_dhcapp_sqluser`.`a`.`paadm_type` = 'I')) AND (`hid0117_cache_his_dhcapp_sqluser`.`a`.`paadm_visitstatus` != 'C')) AND (`hid0117_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr` IS NOT NULL)
GROUP BY `hid0117_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0117_cache_his_dhcapp_sqluser`.`c`.`ctloc_code`, `hid0117_cache_his_dhcapp_sqluser`.`c`.`ctloc_desc`, `hid0117_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0117_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc` UNION ALL SELECT 'HID0120' AS `hosp_code`, `hid0120_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0120_cache_his_dhcapp_sqluser`.`c`.`ctloc_code`, `hid0120_cache_his_dhcapp_sqluser`.`c`.`ctloc_desc`, `hid0120_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0120_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc`, count(DISTINCT `hid0120_cache_his_dhcapp_sqluser`.`a`.`paadm_admno`) AS `ssryresult`, current_timestamp() AS `lastupdatedttm`
FROM `hid0120_cache_his_dhcapp_sqluser`.`pa_adm` AS `a` LEFT OUTER JOIN `hid0120_cache_his_dhcapp_sqluser`.`ct_loc` AS `c` ON `hid0120_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr` = `hid0120_cache_his_dhcapp_sqluser`.`c`.`ctloc_rowid` LEFT OUTER JOIN `hid0120_cache_his_dhcapp_sqluser`.`pac_ward` AS `pac_ward` ON `hid0120_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_rowid` = `hid0120_cache_his_dhcapp_sqluser`.`a`.`paadm_currentward_dr`
WHERE ((((CAST(`hid0120_cache_his_dhcapp_sqluser`.`a`.`paadm_admdate` AS VARCHAR)) = (substring(CAST((current_timestamp()) AS VARCHAR), 1, 10))) AND (`hid0120_cache_his_dhcapp_sqluser`.`a`.`paadm_type` = 'I')) AND (`hid0120_cache_his_dhcapp_sqluser`.`a`.`paadm_visitstatus` != 'C')) AND (`hid0120_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr` IS NOT NULL)
GROUP BY `hid0120_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0120_cache_his_dhcapp_sqluser`.`c`.`ctloc_code`, `hid0120_cache_his_dhcapp_sqluser`.`c`.`ctloc_desc`, `hid0120_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0120_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc` UNION ALL SELECT 'HID0122' AS `hosp_code`, `hid0122_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0122_cache_his_dhcapp_sqluser`.`c`.`ctloc_code`, `hid0122_cache_his_dhcapp_sqluser`.`c`.`ctloc_desc`, `hid0122_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0122_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc`, count(DISTINCT `hid0122_cache_his_dhcapp_sqluser`.`a`.`paadm_admno`) AS `ssryresult`, current_timestamp() AS `lastupdatedttm`
FROM `hid0122_cache_his_dhcapp_sqluser`.`pa_adm` AS `a` LEFT OUTER JOIN `hid0122_cache_his_dhcapp_sqluser`.`ct_loc` AS `c` ON `hid0122_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr` = `hid0122_cache_his_dhcapp_sqluser`.`c`.`ctloc_rowid` LEFT OUTER JOIN `hid0122_cache_his_dhcapp_sqluser`.`pac_ward` AS `pac_ward` ON `hid0122_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_rowid` = `hid0122_cache_his_dhcapp_sqluser`.`a`.`paadm_currentward_dr`
WHERE ((((CAST(`hid0122_cache_his_dhcapp_sqluser`.`a`.`paadm_admdate` AS VARCHAR)) = (substring(CAST((current_timestamp()) AS VARCHAR), 1, 10))) AND (`hid0122_cache_his_dhcapp_sqluser`.`a`.`paadm_type` = 'I')) AND (`hid0122_cache_his_dhcapp_sqluser`.`a`.`paadm_visitstatus` != 'C')) AND (`hid0122_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr` IS NOT NULL)
GROUP BY `hid0122_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0122_cache_his_dhcapp_sqluser`.`c`.`ctloc_code`, `hid0122_cache_his_dhcapp_sqluser`.`c`.`ctloc_desc`, `hid0122_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0122_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc` UNION ALL SELECT 'HID0123' AS `hosp_code`, `hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0123_cache_his_dhcapp_sqluser`.`c`.`ctloc_code`, `hid0123_cache_his_dhcapp_sqluser`.`c`.`ctloc_desc`, `hid0123_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0123_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc`, count(DISTINCT `hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_admno`) AS `ssryresult`, current_timestamp() AS `lastupdatedttm`
FROM `hid0123_cache_his_dhcapp_sqluser`.`pa_adm` AS `a` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`ct_loc` AS `c` ON `hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr` = `hid0123_cache_his_dhcapp_sqluser`.`c`.`ctloc_rowid` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`pac_ward` AS `pac_ward` ON `hid0123_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_rowid` = `hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_currentward_dr`
WHERE ((((CAST(`hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_admdate` AS VARCHAR)) = (substring(CAST((current_timestamp()) AS VARCHAR), 1, 10))) AND (`hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_type` = 'I')) AND (`hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_visitstatus` != 'C')) AND (`hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr` IS NOT NULL) AND (`hid0123_cache_his_dhcapp_sqluser`.`c`.`ctloc_hospital_dr` = '2')
GROUP BY `hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0123_cache_his_dhcapp_sqluser`.`c`.`ctloc_code`, `hid0123_cache_his_dhcapp_sqluser`.`c`.`ctloc_desc`, `hid0123_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0123_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc` UNION ALL SELECT 'HID0124' AS `hosp_code`, `hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0123_cache_his_dhcapp_sqluser`.`c`.`ctloc_code`, `hid0123_cache_his_dhcapp_sqluser`.`c`.`ctloc_desc`, `hid0123_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0123_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc`, count(DISTINCT `hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_admno`) AS `ssryresult`, current_timestamp() AS `lastupdatedttm`
FROM `hid0123_cache_his_dhcapp_sqluser`.`pa_adm` AS `a` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`ct_loc` AS `c` ON `hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr` = `hid0123_cache_his_dhcapp_sqluser`.`c`.`ctloc_rowid` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`pac_ward` AS `pac_ward` ON `hid0123_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_rowid` = `hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_currentward_dr`
WHERE ((((CAST(`hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_admdate` AS VARCHAR)) = (substring(CAST((current_timestamp()) AS VARCHAR), 1, 10))) AND (`hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_type` = 'I')) AND (`hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_visitstatus` != 'C')) AND (`hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr` IS NOT NULL) AND (`hid0123_cache_his_dhcapp_sqluser`.`c`.`ctloc_hospital_dr` = '12')
GROUP BY `hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0123_cache_his_dhcapp_sqluser`.`c`.`ctloc_code`, `hid0123_cache_his_dhcapp_sqluser`.`c`.`ctloc_desc`, `hid0123_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0123_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc`;

CREATE MATERIALIZED VIEW `indicators`.`currentzyxz_v3` (`hosp_code`, `paadm_depcode_dr`, `ctloc_code`, `ctloc_desc`, `ward_code`, `ward_desc`, `sszyresult`, `lastupdatedttm`, `rowkey`)
COMMENT "实时在院人次"
DISTRIBUTED BY HASH(`hosp_code`)
REFRESH ASYNC EVERY(INTERVAL 180 SECOND)
PROPERTIES (
"replicated_storage" = "true",
"replication_num" = "3",
"storage_medium" = "HDD"
)
AS SELECT `a`.`hosp_code`, `a`.`paadm_depcode_dr`, `a`.`ctloc_code`, `a`.`ctloc_desc`, `a`.`ward_code`, `a`.`ward_desc`, `a`.`sszyresult`, `a`.`lastupdatedttm`, `a`.`rowkey`
FROM (SELECT 'HID0101' AS `hosp_code`, `hid0101_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0101_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0101_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0101_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0101_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc`, CAST((count(DISTINCT `hid0101_cache_his_dhcapp_sqluser`.`a`.`paadm_admno`)) AS INT) AS `sszyresult`, current_timestamp() AS `lastupdatedttm`, concat('HID0101_2_', CAST((current_timestamp()) AS VARCHAR), `hid0101_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`) AS `rowkey`
FROM `hid0101_cache_his_dhcapp_sqluser`.`pa_adm` AS `a` LEFT OUTER JOIN `hid0101_cache_his_dhcapp_sqluser`.`ct_loc` AS `b` ON `hid0101_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr` = `hid0101_cache_his_dhcapp_sqluser`.`b`.`ctloc_rowid` LEFT OUTER JOIN `hid0101_cache_his_dhcapp_sqluser`.`pac_ward` AS `pac_ward` ON `hid0101_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_rowid` = `hid0101_cache_his_dhcapp_sqluser`.`a`.`paadm_currentward_dr`
WHERE ((`hid0101_cache_his_dhcapp_sqluser`.`a`.`paadm_rowid` NOT IN (((((SELECT `indicators`.`tmp_exclude_ids`.`id`
FROM `indicators`.`tmp_exclude_ids`)))))) AND ((`hid0101_cache_his_dhcapp_sqluser`.`a`.`paadm_type` = 'I') AND (`hid0101_cache_his_dhcapp_sqluser`.`a`.`paadm_visitstatus` = 'A'))) AND (`hid0101_cache_his_dhcapp_sqluser`.`a`.`paadm_currentbed_dr` IS NOT NULL)
GROUP BY `hid0101_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0101_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0101_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0101_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0101_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc` UNION ALL SELECT 'HID0103' AS `hosp_code`, `hid0103_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0103_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0103_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0103_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0103_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc`, CAST((count(DISTINCT `hid0103_cache_his_dhcapp_sqluser`.`a`.`paadm_admno`)) AS INT) AS `sszyresult`, current_timestamp() AS `lastupdatedttm`, concat('HID0103_2_', CAST((current_timestamp()) AS VARCHAR), `hid0103_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`) AS `rowkey`
FROM `hid0103_cache_his_dhcapp_sqluser`.`pa_adm` AS `a` LEFT OUTER JOIN `hid0103_cache_his_dhcapp_sqluser`.`ct_loc` AS `b` ON `hid0103_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr` = `hid0103_cache_his_dhcapp_sqluser`.`b`.`ctloc_rowid` LEFT OUTER JOIN `hid0103_cache_his_dhcapp_sqluser`.`pac_ward` AS `pac_ward` ON `hid0103_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_rowid` = `hid0103_cache_his_dhcapp_sqluser`.`a`.`paadm_currentward_dr`
WHERE ((`hid0103_cache_his_dhcapp_sqluser`.`a`.`paadm_type` = 'I') AND (`hid0103_cache_his_dhcapp_sqluser`.`a`.`paadm_visitstatus` = 'A')) AND (`hid0103_cache_his_dhcapp_sqluser`.`a`.`paadm_currentbed_dr` IS NOT NULL)
GROUP BY `hid0103_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0103_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0103_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0103_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0103_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc` UNION ALL SELECT 'HID0117' AS `hosp_code`, `hid0117_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0117_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0117_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0117_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0117_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc`, CAST((count(DISTINCT `hid0117_cache_his_dhcapp_sqluser`.`a`.`paadm_admno`)) AS INT) AS `sszyresult`, current_timestamp() AS `lastupdatedttm`, concat('HID0117_1_', CAST((current_timestamp()) AS VARCHAR), `hid0117_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`) AS `rowkey`
FROM `hid0117_cache_his_dhcapp_sqluser`.`pa_adm` AS `a` LEFT OUTER JOIN `hid0117_cache_his_dhcapp_sqluser`.`ct_loc` AS `b` ON `hid0117_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr` = `hid0117_cache_his_dhcapp_sqluser`.`b`.`ctloc_rowid` LEFT OUTER JOIN `hid0117_cache_his_dhcapp_sqluser`.`pac_ward` AS `pac_ward` ON `hid0117_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_rowid` = `hid0117_cache_his_dhcapp_sqluser`.`a`.`paadm_currentward_dr`
WHERE ((`hid0117_cache_his_dhcapp_sqluser`.`a`.`paadm_type` = 'I') AND (`hid0117_cache_his_dhcapp_sqluser`.`a`.`paadm_visitstatus` = 'A')) AND (`hid0117_cache_his_dhcapp_sqluser`.`a`.`paadm_currentbed_dr` IS NOT NULL)
GROUP BY `hid0117_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0117_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0117_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0117_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0117_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc`) `a`
WHERE NOT (`a`.`ctloc_desc` LIKE '%测试%') UNION ALL SELECT 'HID0120' AS `hosp_code`, `hid0120_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0120_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0120_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0120_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0120_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc`, CAST((count(DISTINCT `hid0120_cache_his_dhcapp_sqluser`.`a`.`paadm_admno`)) AS INT) AS `sszyresult`, current_timestamp() AS `lastupdatedttm`, concat('HID0120_2_', CAST((current_timestamp()) AS VARCHAR), `hid0120_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`) AS `rowkey`
FROM `hid0120_cache_his_dhcapp_sqluser`.`pa_adm` AS `a` LEFT OUTER JOIN `hid0120_cache_his_dhcapp_sqluser`.`ct_loc` AS `b` ON `hid0120_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr` = `hid0120_cache_his_dhcapp_sqluser`.`b`.`ctloc_rowid` LEFT OUTER JOIN `hid0120_cache_his_dhcapp_sqluser`.`pac_ward` AS `pac_ward` ON `hid0120_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_rowid` = `hid0120_cache_his_dhcapp_sqluser`.`a`.`paadm_currentward_dr`
WHERE ((`hid0120_cache_his_dhcapp_sqluser`.`a`.`paadm_type` = 'I') AND (`hid0120_cache_his_dhcapp_sqluser`.`a`.`paadm_visitstatus` = 'A')) AND (`hid0120_cache_his_dhcapp_sqluser`.`a`.`paadm_currentbed_dr` IS NOT NULL)
GROUP BY `hid0120_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0120_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0120_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0120_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0120_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc` UNION ALL SELECT 'HID0122' AS `hosp_code`, `hid0122_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0122_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0122_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0122_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0122_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc`, CAST((count(DISTINCT `hid0122_cache_his_dhcapp_sqluser`.`a`.`paadm_admno`)) AS INT) AS `sszyresult`, current_timestamp() AS `lastupdatedttm`, concat('HID0122_2_', CAST((current_timestamp()) AS VARCHAR), `hid0122_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`) AS `rowkey`
FROM `hid0122_cache_his_dhcapp_sqluser`.`pa_adm` AS `a` LEFT OUTER JOIN `hid0122_cache_his_dhcapp_sqluser`.`ct_loc` AS `b` ON `hid0122_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr` = `hid0122_cache_his_dhcapp_sqluser`.`b`.`ctloc_rowid` LEFT OUTER JOIN `hid0122_cache_his_dhcapp_sqluser`.`pac_ward` AS `pac_ward` ON `hid0122_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_rowid` = `hid0122_cache_his_dhcapp_sqluser`.`a`.`paadm_currentward_dr`
WHERE ((`hid0122_cache_his_dhcapp_sqluser`.`a`.`paadm_type` = 'I') AND (`hid0122_cache_his_dhcapp_sqluser`.`a`.`paadm_visitstatus` = 'A')) AND (`hid0122_cache_his_dhcapp_sqluser`.`a`.`paadm_currentbed_dr` IS NOT NULL)
GROUP BY `hid0122_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0122_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0122_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0122_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0122_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc` UNION ALL SELECT 'HID0123' AS `hosp_code`, `hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0123_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0123_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc`, CAST((count(DISTINCT `hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_admno`)) AS INT) AS `sszyresult`, current_timestamp() AS `lastupdatedttm`, concat('HID0123_2_', CAST((current_timestamp()) AS VARCHAR), `hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`) AS `rowkey`
FROM `hid0123_cache_his_dhcapp_sqluser`.`pa_adm` AS `a` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`ct_loc` AS `b` ON `hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr` = `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_rowid` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`pac_ward` AS `pac_ward` ON `hid0123_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_rowid` = `hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_currentward_dr`
WHERE ((`hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_type` = 'I') AND (`hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_visitstatus` = 'A')) AND (`hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_currentbed_dr` IS NOT NULL) AND (`hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_hospital_dr` = '2')
GROUP BY `hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0123_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0123_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc` UNION ALL SELECT 'HID0124' AS `hosp_code`, `hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0123_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0123_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc`, CAST((count(DISTINCT `hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_admno`)) AS INT) AS `sszyresult`, current_timestamp() AS `lastupdatedttm`, concat('HID0124_2_', CAST((current_timestamp()) AS VARCHAR), `hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`) AS `rowkey`
FROM `hid0123_cache_his_dhcapp_sqluser`.`pa_adm` AS `a` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`ct_loc` AS `b` ON `hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr` = `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_rowid` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`pac_ward` AS `pac_ward` ON `hid0123_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_rowid` = `hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_currentward_dr`
WHERE ((`hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_type` = 'I') AND (`hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_visitstatus` = 'A')) AND (`hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_currentbed_dr` IS NOT NULL) AND (`hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_hospital_dr` = '12')
GROUP BY `hid0123_cache_his_dhcapp_sqluser`.`a`.`paadm_depcode_dr`, `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0123_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_code`, `hid0123_cache_his_dhcapp_sqluser`.`pac_ward`.`ward_desc`;

CREATE MATERIALIZED VIEW `indicators`.`currtime_income_v3` (`hosp_code`, `abdate`, `paadmtype`, `tectype`, `ordloc_code`, `ordloc`, `recloc_code`, `recloc`, `patloccode`, `patloc`, `patwardcode`, `patward`, `totalfee`, `lastupdatedttm`)
COMMENT "实时收入"
DISTRIBUTED BY HASH(`hosp_code`)
REFRESH ASYNC EVERY(INTERVAL 180 SECOND)
PROPERTIES (
"replicated_storage" = "true",
"replication_num" = "3",
"storage_medium" = "HDD"
)
AS SELECT 'HID0101' AS `hosp_code`, `hid0101_cache_his_dhcapp_sqluser`.`billdet`.`pbd_createdate` AS `abdate`, `hid0101_cache_his_dhcapp_sqluser`.`adm`.`paadm_type` AS `paadmtype`, `hid0101_cache_his_dhcapp_sqluser`.`tarec`.`tartec_desc` AS `tectype`, `hid0101_cache_his_dhcapp_sqluser`.`ctloc`.`ctloc_code` AS `ordloc_code`, `hid0101_cache_his_dhcapp_sqluser`.`ctloc`.`ctloc_desc` AS `ordloc`, `hid0101_cache_his_dhcapp_sqluser`.`ctlocjs`.`ctloc_code` AS `recloc_code`, `hid0101_cache_his_dhcapp_sqluser`.`ctlocjs`.`ctloc_desc` AS `recloc`, `hid0101_cache_his_dhcapp_sqluser`.`ctlocjzks`.`ctloc_code` AS `patloccode`, `hid0101_cache_his_dhcapp_sqluser`.`ctlocjzks`.`ctloc_desc` AS `patloc`, `hid0101_cache_his_dhcapp_sqluser`.`zyward`.`ward_code` AS `patwardcode`, `hid0101_cache_his_dhcapp_sqluser`.`zyward`.`ward_desc` AS `patward`, CAST((sum(CASE WHEN ((abs(CAST(`hid0101_cache_his_dhcapp_sqluser`.`billdet`.`pbd_totalamount` AS DECIMAL64(18,4)))) > (abs((CAST(`hid0101_cache_his_dhcapp_sqluser`.`billdet`.`pbd_totalamount` AS DECIMAL64(18,4))) - (coalesce(CAST(`hid0101_cache_his_dhcapp_sqluser`.`billdet`.`pbd_discamount` AS DECIMAL64(18,4)), 0))))) THEN (CAST(`hid0101_cache_his_dhcapp_sqluser`.`billdet`.`pbd_totalamount` AS DECIMAL64(18,4))) ELSE ((CAST(`hid0101_cache_his_dhcapp_sqluser`.`billdet`.`pbd_totalamount` AS DECIMAL64(18,4))) - (coalesce(CAST(`hid0101_cache_his_dhcapp_sqluser`.`billdet`.`pbd_discamount` AS DECIMAL64(18,4)), 0))) END)) AS DOUBLE) AS `totalfee`, current_timestamp() AS `lastupdatedttm`
FROM `hid0101_cache_his_dhcapp_sqluser`.`dhc_patbilldetails` AS `billdet` LEFT OUTER JOIN `hid0101_cache_his_dhcapp_sqluser`.`dhc_patbillorder` AS `pbo` ON `hid0101_cache_his_dhcapp_sqluser`.`billdet`.`pbd_pbo_parref` = `hid0101_cache_his_dhcapp_sqluser`.`pbo`.`pbo_rowid` LEFT OUTER JOIN `hid0101_cache_his_dhcapp_sqluser`.`dhc_patientbill` AS `bill` ON `hid0101_cache_his_dhcapp_sqluser`.`bill`.`pb_rowid` = `hid0101_cache_his_dhcapp_sqluser`.`pbo`.`pbo_pb_parref` LEFT OUTER JOIN `hid0101_cache_his_dhcapp_sqluser`.`pa_adm` AS `adm` ON `hid0101_cache_his_dhcapp_sqluser`.`bill`.`pb_adm_dr` = `hid0101_cache_his_dhcapp_sqluser`.`adm`.`paadm_rowid` LEFT OUTER JOIN `hid0101_cache_his_dhcapp_sqluser`.`dhc_taritem` AS `taritem` ON `hid0101_cache_his_dhcapp_sqluser`.`billdet`.`pbd_tari_dr` = `hid0101_cache_his_dhcapp_sqluser`.`taritem`.`tari_rowid` LEFT OUTER JOIN `hid0101_cache_his_dhcapp_sqluser`.`dhc_taremccate` AS `taremc` ON `hid0101_cache_his_dhcapp_sqluser`.`taritem`.`tari_emccate` = `hid0101_cache_his_dhcapp_sqluser`.`taremc`.`tarec_rowid` LEFT OUTER JOIN `hid0101_cache_his_dhcapp_sqluser`.`dhc_tarec` AS `tarec` ON `hid0101_cache_his_dhcapp_sqluser`.`tarec`.`tartec_rowid` = `hid0101_cache_his_dhcapp_sqluser`.`taremc`.`tarec_tartec_dr` LEFT OUTER JOIN `hid0101_cache_his_dhcapp_sqluser`.`oe_orditem` AS `oeori` ON `hid0101_cache_his_dhcapp_sqluser`.`oeori`.`oeori_rowid` = `hid0101_cache_his_dhcapp_sqluser`.`pbo`.`pbo_oeori_dr` LEFT OUTER JOIN `hid0101_cache_his_dhcapp_sqluser`.`ct_loc` AS `ctloc` ON `hid0101_cache_his_dhcapp_sqluser`.`oeori`.`oeori_orddept_dr` = `hid0101_cache_his_dhcapp_sqluser`.`ctloc`.`ctloc_rowid` LEFT OUTER JOIN `hid0101_cache_his_dhcapp_sqluser`.`ct_loc` AS `ctlocjs` ON `hid0101_cache_his_dhcapp_sqluser`.`oeori`.`oeori_recdep_dr` = `hid0101_cache_his_dhcapp_sqluser`.`ctlocjs`.`ctloc_rowid` LEFT OUTER JOIN `hid0101_cache_his_dhcapp_sqluser`.`ct_loc` AS `ctlocjzks` ON `hid0101_cache_his_dhcapp_sqluser`.`adm`.`paadm_depcode_dr` = `hid0101_cache_his_dhcapp_sqluser`.`ctlocjzks`.`ctloc_rowid` LEFT OUTER JOIN `hid0101_cache_his_dhcapp_sqluser`.`pac_ward` AS `zyward` ON `hid0101_cache_his_dhcapp_sqluser`.`adm`.`paadm_currentward_dr` = `hid0101_cache_his_dhcapp_sqluser`.`zyward`.`ward_rowid`
WHERE ((`hid0101_cache_his_dhcapp_sqluser`.`adm`.`paadm_rowid` NOT IN (((((SELECT `indicators`.`tmp_exclude_ids`.`id`
FROM `indicators`.`tmp_exclude_ids`)))))) AND (((`hid0101_cache_his_dhcapp_sqluser`.`billdet`.`pbd_createdate` = (CAST((current_date()) AS VARCHAR))) AND (`hid0101_cache_his_dhcapp_sqluser`.`billdet`.`isdeleted` = '0')) AND ((length(`hid0101_cache_his_dhcapp_sqluser`.`billdet`.`pbd_totalamount`)) < 12))) AND (((`hid0101_cache_his_dhcapp_sqluser`.`adm`.`paadm_type` = 'I') OR ((`hid0101_cache_his_dhcapp_sqluser`.`adm`.`paadm_type` = 'O') AND (`hid0101_cache_his_dhcapp_sqluser`.`bill`.`pb_payedflag` = 'P'))) OR ((`hid0101_cache_his_dhcapp_sqluser`.`adm`.`paadm_type` = 'E') AND ((`hid0101_cache_his_dhcapp_sqluser`.`bill`.`pb_payedflag` = 'P') OR (`hid0101_cache_his_dhcapp_sqluser`.`adm`.`paadm_currentward_dr` IS NOT NULL))))
GROUP BY `hid0101_cache_his_dhcapp_sqluser`.`billdet`.`pbd_createdate`, `hid0101_cache_his_dhcapp_sqluser`.`adm`.`paadm_type`, `hid0101_cache_his_dhcapp_sqluser`.`tarec`.`tartec_desc`, `hid0101_cache_his_dhcapp_sqluser`.`ctloc`.`ctloc_code`, `hid0101_cache_his_dhcapp_sqluser`.`ctloc`.`ctloc_desc`, `hid0101_cache_his_dhcapp_sqluser`.`ctlocjs`.`ctloc_code`, `hid0101_cache_his_dhcapp_sqluser`.`ctlocjs`.`ctloc_desc`, `hid0101_cache_his_dhcapp_sqluser`.`ctlocjzks`.`ctloc_desc`, `hid0101_cache_his_dhcapp_sqluser`.`zyward`.`ward_desc`, `hid0101_cache_his_dhcapp_sqluser`.`ctlocjzks`.`ctloc_code`, `hid0101_cache_his_dhcapp_sqluser`.`zyward`.`ward_code` UNION ALL SELECT 'HID0103' AS `hosp_code`, `hid0103_cache_his_dhcapp_sqluser`.`billdet`.`pbd_createdate` AS `abdate`, `hid0103_cache_his_dhcapp_sqluser`.`adm`.`paadm_type` AS `paadmtype`, `hid0103_cache_his_dhcapp_sqluser`.`tarec`.`tartec_desc` AS `tectype`, `hid0103_cache_his_dhcapp_sqluser`.`ctloc`.`ctloc_code` AS `ordloc_code`, `hid0103_cache_his_dhcapp_sqluser`.`ctloc`.`ctloc_desc` AS `ordloc`, `hid0103_cache_his_dhcapp_sqluser`.`ctlocjs`.`ctloc_code` AS `recloc_code`, `hid0103_cache_his_dhcapp_sqluser`.`ctlocjs`.`ctloc_desc` AS `recloc`, `hid0103_cache_his_dhcapp_sqluser`.`ctlocjzks`.`ctloc_code` AS `patloccode`, `hid0103_cache_his_dhcapp_sqluser`.`ctlocjzks`.`ctloc_desc` AS `patloc`, `hid0103_cache_his_dhcapp_sqluser`.`zyward`.`ward_code` AS `patwardcode`, `hid0103_cache_his_dhcapp_sqluser`.`zyward`.`ward_desc` AS `patward`, CAST((sum(CASE WHEN ((abs(CAST(`hid0103_cache_his_dhcapp_sqluser`.`billdet`.`pbd_totalamount` AS DECIMAL64(18,4)))) > (abs((CAST(`hid0103_cache_his_dhcapp_sqluser`.`billdet`.`pbd_totalamount` AS DECIMAL64(18,4))) - (coalesce(CAST(`hid0103_cache_his_dhcapp_sqluser`.`billdet`.`pbd_discamount` AS DECIMAL64(18,4)), 0))))) THEN (CAST(`hid0103_cache_his_dhcapp_sqluser`.`billdet`.`pbd_totalamount` AS DECIMAL64(18,4))) ELSE ((CAST(`hid0103_cache_his_dhcapp_sqluser`.`billdet`.`pbd_totalamount` AS DECIMAL64(18,4))) - (coalesce(CAST(`hid0103_cache_his_dhcapp_sqluser`.`billdet`.`pbd_discamount` AS DECIMAL64(18,4)), 0))) END)) AS DOUBLE) AS `totalfee`, current_timestamp() AS `lastupdatedttm`
FROM `hid0103_cache_his_dhcapp_sqluser`.`dhc_patbilldetails` AS `billdet` LEFT OUTER JOIN `hid0103_cache_his_dhcapp_sqluser`.`dhc_patbillorder` AS `pbo` ON `hid0103_cache_his_dhcapp_sqluser`.`billdet`.`pbd_pbo_parref` = `hid0103_cache_his_dhcapp_sqluser`.`pbo`.`pbo_rowid` LEFT OUTER JOIN `hid0103_cache_his_dhcapp_sqluser`.`dhc_patientbill` AS `bill` ON `hid0103_cache_his_dhcapp_sqluser`.`bill`.`pb_rowid` = `hid0103_cache_his_dhcapp_sqluser`.`pbo`.`pbo_pb_parref` LEFT OUTER JOIN `hid0103_cache_his_dhcapp_sqluser`.`pa_adm` AS `adm` ON `hid0103_cache_his_dhcapp_sqluser`.`bill`.`pb_adm_dr` = `hid0103_cache_his_dhcapp_sqluser`.`adm`.`paadm_rowid` LEFT OUTER JOIN `hid0103_cache_his_dhcapp_sqluser`.`dhc_taritem` AS `taritem` ON `hid0103_cache_his_dhcapp_sqluser`.`billdet`.`pbd_tari_dr` = `hid0103_cache_his_dhcapp_sqluser`.`taritem`.`tari_rowid` LEFT OUTER JOIN `hid0103_cache_his_dhcapp_sqluser`.`dhc_taremccate` AS `taremc` ON `hid0103_cache_his_dhcapp_sqluser`.`taritem`.`tari_emccate` = `hid0103_cache_his_dhcapp_sqluser`.`taremc`.`tarec_rowid` LEFT OUTER JOIN `hid0103_cache_his_dhcapp_sqluser`.`dhc_tarec` AS `tarec` ON `hid0103_cache_his_dhcapp_sqluser`.`tarec`.`tartec_rowid` = `hid0103_cache_his_dhcapp_sqluser`.`taremc`.`tarec_tartec_dr` LEFT OUTER JOIN `hid0103_cache_his_dhcapp_sqluser`.`oe_orditem` AS `oeori` ON `hid0103_cache_his_dhcapp_sqluser`.`oeori`.`oeori_rowid` = `hid0103_cache_his_dhcapp_sqluser`.`pbo`.`pbo_oeori_dr` LEFT OUTER JOIN `hid0103_cache_his_dhcapp_sqluser`.`ct_loc` AS `ctloc` ON `hid0103_cache_his_dhcapp_sqluser`.`oeori`.`oeori_orddept_dr` = `hid0103_cache_his_dhcapp_sqluser`.`ctloc`.`ctloc_rowid` LEFT OUTER JOIN `hid0103_cache_his_dhcapp_sqluser`.`ct_loc` AS `ctlocjs` ON `hid0103_cache_his_dhcapp_sqluser`.`oeori`.`oeori_recdep_dr` = `hid0103_cache_his_dhcapp_sqluser`.`ctlocjs`.`ctloc_rowid` LEFT OUTER JOIN `hid0103_cache_his_dhcapp_sqluser`.`ct_loc` AS `ctlocjzks` ON `hid0103_cache_his_dhcapp_sqluser`.`adm`.`paadm_depcode_dr` = `hid0103_cache_his_dhcapp_sqluser`.`ctlocjzks`.`ctloc_rowid` LEFT OUTER JOIN `hid0103_cache_his_dhcapp_sqluser`.`pac_ward` AS `zyward` ON `hid0103_cache_his_dhcapp_sqluser`.`adm`.`paadm_currentward_dr` = `hid0103_cache_his_dhcapp_sqluser`.`zyward`.`ward_rowid`
WHERE (((`hid0103_cache_his_dhcapp_sqluser`.`billdet`.`pbd_createdate` = (CAST((current_date()) AS VARCHAR))) AND (`hid0103_cache_his_dhcapp_sqluser`.`billdet`.`isdeleted` = '0')) AND ((length(`hid0103_cache_his_dhcapp_sqluser`.`billdet`.`pbd_totalamount`)) < 12)) AND (((`hid0103_cache_his_dhcapp_sqluser`.`adm`.`paadm_type` = 'I') OR ((`hid0103_cache_his_dhcapp_sqluser`.`adm`.`paadm_type` = 'O') AND (`hid0103_cache_his_dhcapp_sqluser`.`bill`.`pb_payedflag` = 'P'))) OR ((`hid0103_cache_his_dhcapp_sqluser`.`adm`.`paadm_type` = 'E') AND ((`hid0103_cache_his_dhcapp_sqluser`.`bill`.`pb_payedflag` = 'P') OR (`hid0103_cache_his_dhcapp_sqluser`.`adm`.`paadm_currentward_dr` IS NOT NULL))))
GROUP BY `hid0103_cache_his_dhcapp_sqluser`.`billdet`.`pbd_createdate`, `hid0103_cache_his_dhcapp_sqluser`.`adm`.`paadm_type`, `hid0103_cache_his_dhcapp_sqluser`.`tarec`.`tartec_desc`, `hid0103_cache_his_dhcapp_sqluser`.`ctloc`.`ctloc_code`, `hid0103_cache_his_dhcapp_sqluser`.`ctloc`.`ctloc_desc`, `hid0103_cache_his_dhcapp_sqluser`.`ctlocjs`.`ctloc_code`, `hid0103_cache_his_dhcapp_sqluser`.`ctlocjs`.`ctloc_desc`, `hid0103_cache_his_dhcapp_sqluser`.`ctlocjzks`.`ctloc_desc`, `hid0103_cache_his_dhcapp_sqluser`.`zyward`.`ward_desc`, `hid0103_cache_his_dhcapp_sqluser`.`ctlocjzks`.`ctloc_code`, `hid0103_cache_his_dhcapp_sqluser`.`zyward`.`ward_code` UNION ALL SELECT 'HID0117' AS `hosp_code`, `hid0117_cache_his_dhcapp_sqluser`.`billdet`.`pbd_createdate` AS `abdate`, `hid0117_cache_his_dhcapp_sqluser`.`adm`.`paadm_type` AS `paadmtype`, `hid0117_cache_his_dhcapp_sqluser`.`tarec`.`tartec_desc` AS `tectype`, `hid0117_cache_his_dhcapp_sqluser`.`ctloc`.`ctloc_code` AS `ordloc_code`, `hid0117_cache_his_dhcapp_sqluser`.`ctloc`.`ctloc_desc` AS `ordloc`, `hid0117_cache_his_dhcapp_sqluser`.`ctlocjs`.`ctloc_code` AS `recloc_code`, `hid0117_cache_his_dhcapp_sqluser`.`ctlocjs`.`ctloc_desc` AS `recloc`, `hid0117_cache_his_dhcapp_sqluser`.`ctlocjzks`.`ctloc_code` AS `patloccode`, `hid0117_cache_his_dhcapp_sqluser`.`ctlocjzks`.`ctloc_desc` AS `patloc`, `hid0117_cache_his_dhcapp_sqluser`.`zyward`.`ward_code` AS `patwardcode`, `hid0117_cache_his_dhcapp_sqluser`.`zyward`.`ward_desc` AS `patward`, CAST((sum(CASE WHEN ((abs(CAST(`hid0117_cache_his_dhcapp_sqluser`.`billdet`.`pbd_totalamount` AS DECIMAL64(18,4)))) > (abs((CAST(`hid0117_cache_his_dhcapp_sqluser`.`billdet`.`pbd_totalamount` AS DECIMAL64(18,4))) - (coalesce(CAST(`hid0117_cache_his_dhcapp_sqluser`.`billdet`.`pbd_discamount` AS DECIMAL64(18,4)), 0))))) THEN (CAST(`hid0117_cache_his_dhcapp_sqluser`.`billdet`.`pbd_totalamount` AS DECIMAL64(18,4))) ELSE ((CAST(`hid0117_cache_his_dhcapp_sqluser`.`billdet`.`pbd_totalamount` AS DECIMAL64(18,4))) - (coalesce(CAST(`hid0117_cache_his_dhcapp_sqluser`.`billdet`.`pbd_discamount` AS DECIMAL64(18,4)), 0))) END)) AS DOUBLE) AS `totalfee`, current_timestamp() AS `lastupdatedttm`
FROM `hid0117_cache_his_dhcapp_sqluser`.`dhc_patbilldetails` AS `billdet` LEFT OUTER JOIN `hid0117_cache_his_dhcapp_sqluser`.`dhc_patbillorder` AS `pbo` ON `hid0117_cache_his_dhcapp_sqluser`.`billdet`.`pbd_pbo_parref` = `hid0117_cache_his_dhcapp_sqluser`.`pbo`.`pbo_rowid` LEFT OUTER JOIN `hid0117_cache_his_dhcapp_sqluser`.`dhc_patientbill` AS `bill` ON `hid0117_cache_his_dhcapp_sqluser`.`bill`.`pb_rowid` = `hid0117_cache_his_dhcapp_sqluser`.`pbo`.`pbo_pb_parref` LEFT OUTER JOIN `hid0117_cache_his_dhcapp_sqluser`.`pa_adm` AS `adm` ON `hid0117_cache_his_dhcapp_sqluser`.`bill`.`pb_adm_dr` = `hid0117_cache_his_dhcapp_sqluser`.`adm`.`paadm_rowid` LEFT OUTER JOIN `hid0117_cache_his_dhcapp_sqluser`.`dhc_taritem` AS `taritem` ON `hid0117_cache_his_dhcapp_sqluser`.`billdet`.`pbd_tari_dr` = `hid0117_cache_his_dhcapp_sqluser`.`taritem`.`tari_rowid` LEFT OUTER JOIN `hid0117_cache_his_dhcapp_sqluser`.`dhc_taremccate` AS `taremc` ON `hid0117_cache_his_dhcapp_sqluser`.`taritem`.`tari_emccate` = `hid0117_cache_his_dhcapp_sqluser`.`taremc`.`tarec_rowid` LEFT OUTER JOIN `hid0117_cache_his_dhcapp_sqluser`.`dhc_tarec` AS `tarec` ON `hid0117_cache_his_dhcapp_sqluser`.`tarec`.`tartec_rowid` = `hid0117_cache_his_dhcapp_sqluser`.`taremc`.`tarec_tartec_dr` LEFT OUTER JOIN `hid0117_cache_his_dhcapp_sqluser`.`oe_orditem` AS `oeori` ON `hid0117_cache_his_dhcapp_sqluser`.`oeori`.`oeori_rowid` = `hid0117_cache_his_dhcapp_sqluser`.`pbo`.`pbo_oeori_dr` LEFT OUTER JOIN `hid0117_cache_his_dhcapp_sqluser`.`ct_loc` AS `ctloc` ON `hid0117_cache_his_dhcapp_sqluser`.`oeori`.`oeori_orddept_dr` = `hid0117_cache_his_dhcapp_sqluser`.`ctloc`.`ctloc_rowid` LEFT OUTER JOIN `hid0117_cache_his_dhcapp_sqluser`.`ct_loc` AS `ctlocjs` ON `hid0117_cache_his_dhcapp_sqluser`.`oeori`.`oeori_recdep_dr` = `hid0117_cache_his_dhcapp_sqluser`.`ctlocjs`.`ctloc_rowid` LEFT OUTER JOIN `hid0117_cache_his_dhcapp_sqluser`.`ct_loc` AS `ctlocjzks` ON `hid0117_cache_his_dhcapp_sqluser`.`adm`.`paadm_depcode_dr` = `hid0117_cache_his_dhcapp_sqluser`.`ctlocjzks`.`ctloc_rowid` LEFT OUTER JOIN `hid0117_cache_his_dhcapp_sqluser`.`pac_ward` AS `zyward` ON `hid0117_cache_his_dhcapp_sqluser`.`adm`.`paadm_currentward_dr` = `hid0117_cache_his_dhcapp_sqluser`.`zyward`.`ward_rowid`
WHERE (((`hid0117_cache_his_dhcapp_sqluser`.`billdet`.`pbd_createdate` = (CAST((current_date()) AS VARCHAR))) AND (`hid0117_cache_his_dhcapp_sqluser`.`billdet`.`isdeleted` = '0')) AND ((length(`hid0117_cache_his_dhcapp_sqluser`.`billdet`.`pbd_totalamount`)) < 12)) AND (((`hid0117_cache_his_dhcapp_sqluser`.`adm`.`paadm_type` = 'I') OR ((`hid0117_cache_his_dhcapp_sqluser`.`adm`.`paadm_type` = 'O') AND (`hid0117_cache_his_dhcapp_sqluser`.`bill`.`pb_payedflag` = 'P'))) OR ((`hid0117_cache_his_dhcapp_sqluser`.`adm`.`paadm_type` = 'E') AND ((`hid0117_cache_his_dhcapp_sqluser`.`bill`.`pb_payedflag` = 'P') OR (`hid0117_cache_his_dhcapp_sqluser`.`adm`.`paadm_currentward_dr` IS NOT NULL))))
GROUP BY `hid0117_cache_his_dhcapp_sqluser`.`billdet`.`pbd_createdate`, `hid0117_cache_his_dhcapp_sqluser`.`adm`.`paadm_type`, `hid0117_cache_his_dhcapp_sqluser`.`tarec`.`tartec_desc`, `hid0117_cache_his_dhcapp_sqluser`.`ctloc`.`ctloc_code`, `hid0117_cache_his_dhcapp_sqluser`.`ctloc`.`ctloc_desc`, `hid0117_cache_his_dhcapp_sqluser`.`ctlocjs`.`ctloc_code`, `hid0117_cache_his_dhcapp_sqluser`.`ctlocjs`.`ctloc_desc`, `hid0117_cache_his_dhcapp_sqluser`.`ctlocjzks`.`ctloc_desc`, `hid0117_cache_his_dhcapp_sqluser`.`zyward`.`ward_desc`, `hid0117_cache_his_dhcapp_sqluser`.`ctlocjzks`.`ctloc_code`, `hid0117_cache_his_dhcapp_sqluser`.`zyward`.`ward_code` UNION ALL SELECT 'HID0120' AS `hosp_code`, `hid0120_cache_his_dhcapp_sqluser`.`billdet`.`pbd_createdate` AS `abdate`, `hid0120_cache_his_dhcapp_sqluser`.`adm`.`paadm_type` AS `paadmtype`, `hid0120_cache_his_dhcapp_sqluser`.`tarec`.`tartec_desc` AS `tectype`, `hid0120_cache_his_dhcapp_sqluser`.`ctloc`.`ctloc_code` AS `ordloc_code`, `hid0120_cache_his_dhcapp_sqluser`.`ctloc`.`ctloc_desc` AS `ordloc`, `hid0120_cache_his_dhcapp_sqluser`.`ctlocjs`.`ctloc_code` AS `recloc_code`, `hid0120_cache_his_dhcapp_sqluser`.`ctlocjs`.`ctloc_desc` AS `recloc`, `hid0120_cache_his_dhcapp_sqluser`.`ctlocjzks`.`ctloc_code` AS `patloccode`, `hid0120_cache_his_dhcapp_sqluser`.`ctlocjzks`.`ctloc_desc` AS `patloc`, `hid0120_cache_his_dhcapp_sqluser`.`zyward`.`ward_code` AS `patwardcode`, `hid0120_cache_his_dhcapp_sqluser`.`zyward`.`ward_desc` AS `patward`, CAST((sum(CASE WHEN ((abs(CAST(`hid0120_cache_his_dhcapp_sqluser`.`billdet`.`pbd_totalamount` AS DECIMAL64(18,4)))) > (abs((CAST(`hid0120_cache_his_dhcapp_sqluser`.`billdet`.`pbd_totalamount` AS DECIMAL64(18,4))) - (coalesce(CAST(`hid0120_cache_his_dhcapp_sqluser`.`billdet`.`pbd_discamount` AS DECIMAL64(18,4)), 0))))) THEN (CAST(`hid0120_cache_his_dhcapp_sqluser`.`billdet`.`pbd_totalamount` AS DECIMAL64(18,4))) ELSE ((CAST(`hid0120_cache_his_dhcapp_sqluser`.`billdet`.`pbd_totalamount` AS DECIMAL64(18,4))) - (coalesce(CAST(`hid0120_cache_his_dhcapp_sqluser`.`billdet`.`pbd_discamount` AS DECIMAL64(18,4)), 0))) END)) AS DOUBLE) AS `totalfee`, current_timestamp() AS `lastupdatedttm`
FROM `hid0120_cache_his_dhcapp_sqluser`.`dhc_patbilldetails` AS `billdet` LEFT OUTER JOIN `hid0120_cache_his_dhcapp_sqluser`.`dhc_patbillorder` AS `pbo` ON `hid0120_cache_his_dhcapp_sqluser`.`billdet`.`pbd_pbo_parref` = `hid0120_cache_his_dhcapp_sqluser`.`pbo`.`pbo_rowid` LEFT OUTER JOIN `hid0120_cache_his_dhcapp_sqluser`.`dhc_patientbill` AS `bill` ON `hid0120_cache_his_dhcapp_sqluser`.`bill`.`pb_rowid` = `hid0120_cache_his_dhcapp_sqluser`.`pbo`.`pbo_pb_parref` LEFT OUTER JOIN `hid0120_cache_his_dhcapp_sqluser`.`pa_adm` AS `adm` ON `hid0120_cache_his_dhcapp_sqluser`.`bill`.`pb_adm_dr` = `hid0120_cache_his_dhcapp_sqluser`.`adm`.`paadm_rowid` LEFT OUTER JOIN `hid0120_cache_his_dhcapp_sqluser`.`dhc_taritem` AS `taritem` ON `hid0120_cache_his_dhcapp_sqluser`.`billdet`.`pbd_tari_dr` = `hid0120_cache_his_dhcapp_sqluser`.`taritem`.`tari_rowid` LEFT OUTER JOIN `hid0120_cache_his_dhcapp_sqluser`.`dhc_taremccate` AS `taremc` ON `hid0120_cache_his_dhcapp_sqluser`.`taritem`.`tari_emccate` = `hid0120_cache_his_dhcapp_sqluser`.`taremc`.`tarec_rowid` LEFT OUTER JOIN `hid0120_cache_his_dhcapp_sqluser`.`dhc_tarec` AS `tarec` ON `hid0120_cache_his_dhcapp_sqluser`.`tarec`.`tartec_rowid` = `hid0120_cache_his_dhcapp_sqluser`.`taremc`.`tarec_tartec_dr` LEFT OUTER JOIN `hid0120_cache_his_dhcapp_sqluser`.`oe_orditem` AS `oeori` ON `hid0120_cache_his_dhcapp_sqluser`.`oeori`.`oeori_rowid` = `hid0120_cache_his_dhcapp_sqluser`.`pbo`.`pbo_oeori_dr` LEFT OUTER JOIN `hid0120_cache_his_dhcapp_sqluser`.`ct_loc` AS `ctloc` ON `hid0120_cache_his_dhcapp_sqluser`.`oeori`.`oeori_orddept_dr` = `hid0120_cache_his_dhcapp_sqluser`.`ctloc`.`ctloc_rowid` LEFT OUTER JOIN `hid0120_cache_his_dhcapp_sqluser`.`ct_loc` AS `ctlocjs` ON `hid0120_cache_his_dhcapp_sqluser`.`oeori`.`oeori_recdep_dr` = `hid0120_cache_his_dhcapp_sqluser`.`ctlocjs`.`ctloc_rowid` LEFT OUTER JOIN `hid0120_cache_his_dhcapp_sqluser`.`ct_loc` AS `ctlocjzks` ON `hid0120_cache_his_dhcapp_sqluser`.`adm`.`paadm_depcode_dr` = `hid0120_cache_his_dhcapp_sqluser`.`ctlocjzks`.`ctloc_rowid` LEFT OUTER JOIN `hid0120_cache_his_dhcapp_sqluser`.`pac_ward` AS `zyward` ON `hid0120_cache_his_dhcapp_sqluser`.`adm`.`paadm_currentward_dr` = `hid0120_cache_his_dhcapp_sqluser`.`zyward`.`ward_rowid`
WHERE (((`hid0120_cache_his_dhcapp_sqluser`.`billdet`.`pbd_createdate` = (CAST((current_date()) AS VARCHAR))) AND (`hid0120_cache_his_dhcapp_sqluser`.`billdet`.`isdeleted` = '0')) AND ((length(`hid0120_cache_his_dhcapp_sqluser`.`billdet`.`pbd_totalamount`)) < 12)) AND (((`hid0120_cache_his_dhcapp_sqluser`.`adm`.`paadm_type` = 'I') OR ((`hid0120_cache_his_dhcapp_sqluser`.`adm`.`paadm_type` = 'O') AND (`hid0120_cache_his_dhcapp_sqluser`.`bill`.`pb_payedflag` = 'P'))) OR ((`hid0120_cache_his_dhcapp_sqluser`.`adm`.`paadm_type` = 'E') AND ((`hid0120_cache_his_dhcapp_sqluser`.`bill`.`pb_payedflag` = 'P') OR (`hid0120_cache_his_dhcapp_sqluser`.`adm`.`paadm_currentward_dr` IS NOT NULL))))
GROUP BY `hid0120_cache_his_dhcapp_sqluser`.`billdet`.`pbd_createdate`, `hid0120_cache_his_dhcapp_sqluser`.`adm`.`paadm_type`, `hid0120_cache_his_dhcapp_sqluser`.`tarec`.`tartec_desc`, `hid0120_cache_his_dhcapp_sqluser`.`ctloc`.`ctloc_code`, `hid0120_cache_his_dhcapp_sqluser`.`ctloc`.`ctloc_desc`, `hid0120_cache_his_dhcapp_sqluser`.`ctlocjs`.`ctloc_code`, `hid0120_cache_his_dhcapp_sqluser`.`ctlocjs`.`ctloc_desc`, `hid0120_cache_his_dhcapp_sqluser`.`ctlocjzks`.`ctloc_desc`, `hid0120_cache_his_dhcapp_sqluser`.`zyward`.`ward_desc`, `hid0120_cache_his_dhcapp_sqluser`.`ctlocjzks`.`ctloc_code`, `hid0120_cache_his_dhcapp_sqluser`.`zyward`.`ward_code` UNION ALL SELECT 'HID0122' AS `hosp_code`, `hid0122_cache_his_dhcapp_sqluser`.`billdet`.`pbd_createdate` AS `abdate`, `hid0122_cache_his_dhcapp_sqluser`.`adm`.`paadm_type` AS `paadmtype`, `hid0122_cache_his_dhcapp_sqluser`.`tarec`.`tartec_desc` AS `tectype`, `hid0122_cache_his_dhcapp_sqluser`.`ctloc`.`ctloc_code` AS `ordloc_code`, `hid0122_cache_his_dhcapp_sqluser`.`ctloc`.`ctloc_desc` AS `ordloc`, `hid0122_cache_his_dhcapp_sqluser`.`ctlocjs`.`ctloc_code` AS `recloc_code`, `hid0122_cache_his_dhcapp_sqluser`.`ctlocjs`.`ctloc_desc` AS `recloc`, `hid0122_cache_his_dhcapp_sqluser`.`ctlocjzks`.`ctloc_code` AS `patloccode`, `hid0122_cache_his_dhcapp_sqluser`.`ctlocjzks`.`ctloc_desc` AS `patloc`, `hid0122_cache_his_dhcapp_sqluser`.`zyward`.`ward_code` AS `patwardcode`, `hid0122_cache_his_dhcapp_sqluser`.`zyward`.`ward_desc` AS `patward`, CAST((sum(CASE WHEN ((abs(CAST(`hid0122_cache_his_dhcapp_sqluser`.`billdet`.`pbd_totalamount` AS DECIMAL64(18,4)))) > (abs((CAST(`hid0122_cache_his_dhcapp_sqluser`.`billdet`.`pbd_totalamount` AS DECIMAL64(18,4))) - (coalesce(CAST(`hid0122_cache_his_dhcapp_sqluser`.`billdet`.`pbd_discamount` AS DECIMAL64(18,4)), 0))))) THEN (CAST(`hid0122_cache_his_dhcapp_sqluser`.`billdet`.`pbd_totalamount` AS DECIMAL64(18,4))) ELSE ((CAST(`hid0122_cache_his_dhcapp_sqluser`.`billdet`.`pbd_totalamount` AS DECIMAL64(18,4))) - (coalesce(CAST(`hid0122_cache_his_dhcapp_sqluser`.`billdet`.`pbd_discamount` AS DECIMAL64(18,4)), 0))) END)) AS DOUBLE) AS `totalfee`, current_timestamp() AS `lastupdatedttm`
FROM `hid0122_cache_his_dhcapp_sqluser`.`dhc_patbilldetails` AS `billdet` LEFT OUTER JOIN `hid0122_cache_his_dhcapp_sqluser`.`dhc_patbillorder` AS `pbo` ON `hid0122_cache_his_dhcapp_sqluser`.`billdet`.`pbd_pbo_parref` = `hid0122_cache_his_dhcapp_sqluser`.`pbo`.`pbo_rowid` LEFT OUTER JOIN `hid0122_cache_his_dhcapp_sqluser`.`dhc_patientbill` AS `bill` ON `hid0122_cache_his_dhcapp_sqluser`.`bill`.`pb_rowid` = `hid0122_cache_his_dhcapp_sqluser`.`pbo`.`pbo_pb_parref` LEFT OUTER JOIN `hid0122_cache_his_dhcapp_sqluser`.`pa_adm` AS `adm` ON `hid0122_cache_his_dhcapp_sqluser`.`bill`.`pb_adm_dr` = `hid0122_cache_his_dhcapp_sqluser`.`adm`.`paadm_rowid` LEFT OUTER JOIN `hid0122_cache_his_dhcapp_sqluser`.`dhc_taritem` AS `taritem` ON `hid0122_cache_his_dhcapp_sqluser`.`billdet`.`pbd_tari_dr` = `hid0122_cache_his_dhcapp_sqluser`.`taritem`.`tari_rowid` LEFT OUTER JOIN `hid0122_cache_his_dhcapp_sqluser`.`dhc_taremccate` AS `taremc` ON `hid0122_cache_his_dhcapp_sqluser`.`taritem`.`tari_emccate` = `hid0122_cache_his_dhcapp_sqluser`.`taremc`.`tarec_rowid` LEFT OUTER JOIN `hid0122_cache_his_dhcapp_sqluser`.`dhc_tarec` AS `tarec` ON `hid0122_cache_his_dhcapp_sqluser`.`tarec`.`tartec_rowid` = `hid0122_cache_his_dhcapp_sqluser`.`taremc`.`tarec_tartec_dr` LEFT OUTER JOIN `hid0122_cache_his_dhcapp_sqluser`.`oe_orditem` AS `oeori` ON `hid0122_cache_his_dhcapp_sqluser`.`oeori`.`oeori_rowid` = `hid0122_cache_his_dhcapp_sqluser`.`pbo`.`pbo_oeori_dr` LEFT OUTER JOIN `hid0122_cache_his_dhcapp_sqluser`.`ct_loc` AS `ctloc` ON `hid0122_cache_his_dhcapp_sqluser`.`oeori`.`oeori_orddept_dr` = `hid0122_cache_his_dhcapp_sqluser`.`ctloc`.`ctloc_rowid` LEFT OUTER JOIN `hid0122_cache_his_dhcapp_sqluser`.`ct_loc` AS `ctlocjs` ON `hid0122_cache_his_dhcapp_sqluser`.`oeori`.`oeori_recdep_dr` = `hid0122_cache_his_dhcapp_sqluser`.`ctlocjs`.`ctloc_rowid` LEFT OUTER JOIN `hid0122_cache_his_dhcapp_sqluser`.`ct_loc` AS `ctlocjzks` ON `hid0122_cache_his_dhcapp_sqluser`.`adm`.`paadm_depcode_dr` = `hid0122_cache_his_dhcapp_sqluser`.`ctlocjzks`.`ctloc_rowid` LEFT OUTER JOIN `hid0122_cache_his_dhcapp_sqluser`.`pac_ward` AS `zyward` ON `hid0122_cache_his_dhcapp_sqluser`.`adm`.`paadm_currentward_dr` = `hid0122_cache_his_dhcapp_sqluser`.`zyward`.`ward_rowid`
WHERE (((`hid0122_cache_his_dhcapp_sqluser`.`billdet`.`pbd_createdate` = (CAST((current_date()) AS VARCHAR))) AND (`hid0122_cache_his_dhcapp_sqluser`.`billdet`.`isdeleted` = '0')) AND ((length(`hid0122_cache_his_dhcapp_sqluser`.`billdet`.`pbd_totalamount`)) < 12)) AND (((`hid0122_cache_his_dhcapp_sqluser`.`adm`.`paadm_type` = 'I') OR ((`hid0122_cache_his_dhcapp_sqluser`.`adm`.`paadm_type` = 'O') AND (`hid0122_cache_his_dhcapp_sqluser`.`bill`.`pb_payedflag` = 'P'))) OR ((`hid0122_cache_his_dhcapp_sqluser`.`adm`.`paadm_type` = 'E') AND ((`hid0122_cache_his_dhcapp_sqluser`.`bill`.`pb_payedflag` = 'P') OR (`hid0122_cache_his_dhcapp_sqluser`.`adm`.`paadm_currentward_dr` IS NOT NULL))))
GROUP BY `hid0122_cache_his_dhcapp_sqluser`.`billdet`.`pbd_createdate`, `hid0122_cache_his_dhcapp_sqluser`.`adm`.`paadm_type`, `hid0122_cache_his_dhcapp_sqluser`.`tarec`.`tartec_desc`, `hid0122_cache_his_dhcapp_sqluser`.`ctloc`.`ctloc_code`, `hid0122_cache_his_dhcapp_sqluser`.`ctloc`.`ctloc_desc`, `hid0122_cache_his_dhcapp_sqluser`.`ctlocjs`.`ctloc_code`, `hid0122_cache_his_dhcapp_sqluser`.`ctlocjs`.`ctloc_desc`, `hid0122_cache_his_dhcapp_sqluser`.`ctlocjzks`.`ctloc_desc`, `hid0122_cache_his_dhcapp_sqluser`.`zyward`.`ward_desc`, `hid0122_cache_his_dhcapp_sqluser`.`ctlocjzks`.`ctloc_code`, `hid0122_cache_his_dhcapp_sqluser`.`zyward`.`ward_code` UNION ALL SELECT 'HID0123' AS `hosp_code`, `hid0123_cache_his_dhcapp_sqluser`.`billdet`.`pbd_createdate` AS `abdate`, `hid0123_cache_his_dhcapp_sqluser`.`adm`.`paadm_type` AS `paadmtype`, `hid0123_cache_his_dhcapp_sqluser`.`tarec`.`tartec_desc` AS `tectype`, `hid0123_cache_his_dhcapp_sqluser`.`ctloc`.`ctloc_code` AS `ordloc_code`, `hid0123_cache_his_dhcapp_sqluser`.`ctloc`.`ctloc_desc` AS `ordloc`, `hid0123_cache_his_dhcapp_sqluser`.`ctlocjs`.`ctloc_code` AS `recloc_code`, `hid0123_cache_his_dhcapp_sqluser`.`ctlocjs`.`ctloc_desc` AS `recloc`, `hid0123_cache_his_dhcapp_sqluser`.`ctlocjzks`.`ctloc_code` AS `patloccode`, `hid0123_cache_his_dhcapp_sqluser`.`ctlocjzks`.`ctloc_desc` AS `patloc`, `hid0123_cache_his_dhcapp_sqluser`.`zyward`.`ward_code` AS `patwardcode`, `hid0123_cache_his_dhcapp_sqluser`.`zyward`.`ward_desc` AS `patward`, CAST((sum(CASE WHEN ((abs(CAST(`hid0123_cache_his_dhcapp_sqluser`.`billdet`.`pbd_totalamount` AS DECIMAL64(18,4)))) > (abs((CAST(`hid0123_cache_his_dhcapp_sqluser`.`billdet`.`pbd_totalamount` AS DECIMAL64(18,4))) - (coalesce(CAST(`hid0123_cache_his_dhcapp_sqluser`.`billdet`.`pbd_discamount` AS DECIMAL64(18,4)), 0))))) THEN (CAST(`hid0123_cache_his_dhcapp_sqluser`.`billdet`.`pbd_totalamount` AS DECIMAL64(18,4))) ELSE ((CAST(`hid0123_cache_his_dhcapp_sqluser`.`billdet`.`pbd_totalamount` AS DECIMAL64(18,4))) - (coalesce(CAST(`hid0123_cache_his_dhcapp_sqluser`.`billdet`.`pbd_discamount` AS DECIMAL64(18,4)), 0))) END)) AS DOUBLE) AS `totalfee`, current_timestamp() AS `lastupdatedttm`
FROM `hid0123_cache_his_dhcapp_sqluser`.`dhc_patbilldetails` AS `billdet` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`dhc_patbillorder` AS `pbo` ON `hid0123_cache_his_dhcapp_sqluser`.`billdet`.`pbd_pbo_parref` = `hid0123_cache_his_dhcapp_sqluser`.`pbo`.`pbo_rowid` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`dhc_patientbill` AS `bill` ON `hid0123_cache_his_dhcapp_sqluser`.`bill`.`pb_rowid` = `hid0123_cache_his_dhcapp_sqluser`.`pbo`.`pbo_pb_parref` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`pa_adm` AS `adm` ON `hid0123_cache_his_dhcapp_sqluser`.`bill`.`pb_adm_dr` = `hid0123_cache_his_dhcapp_sqluser`.`adm`.`paadm_rowid` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`dhc_taritem` AS `taritem` ON `hid0123_cache_his_dhcapp_sqluser`.`billdet`.`pbd_tari_dr` = `hid0123_cache_his_dhcapp_sqluser`.`taritem`.`tari_rowid` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`dhc_taremccate` AS `taremc` ON `hid0123_cache_his_dhcapp_sqluser`.`taritem`.`tari_emccate` = `hid0123_cache_his_dhcapp_sqluser`.`taremc`.`tarec_rowid` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`dhc_tarec` AS `tarec` ON `hid0123_cache_his_dhcapp_sqluser`.`tarec`.`tartec_rowid` = `hid0123_cache_his_dhcapp_sqluser`.`taremc`.`tarec_tartec_dr` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`oe_orditem` AS `oeori` ON `hid0123_cache_his_dhcapp_sqluser`.`oeori`.`oeori_rowid` = `hid0123_cache_his_dhcapp_sqluser`.`pbo`.`pbo_oeori_dr` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`ct_loc` AS `ctloc` ON `hid0123_cache_his_dhcapp_sqluser`.`oeori`.`oeori_orddept_dr` = `hid0123_cache_his_dhcapp_sqluser`.`ctloc`.`ctloc_rowid` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`ct_loc` AS `ctlocjs` ON `hid0123_cache_his_dhcapp_sqluser`.`oeori`.`oeori_recdep_dr` = `hid0123_cache_his_dhcapp_sqluser`.`ctlocjs`.`ctloc_rowid` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`ct_loc` AS `ctlocjzks` ON `hid0123_cache_his_dhcapp_sqluser`.`adm`.`paadm_depcode_dr` = `hid0123_cache_his_dhcapp_sqluser`.`ctlocjzks`.`ctloc_rowid` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`pac_ward` AS `zyward` ON `hid0123_cache_his_dhcapp_sqluser`.`adm`.`paadm_currentward_dr` = `hid0123_cache_his_dhcapp_sqluser`.`zyward`.`ward_rowid`
WHERE (((`hid0123_cache_his_dhcapp_sqluser`.`billdet`.`pbd_createdate` = (CAST((current_date()) AS VARCHAR))) AND (`hid0123_cache_his_dhcapp_sqluser`.`billdet`.`isdeleted` = '0')) AND ((length(`hid0123_cache_his_dhcapp_sqluser`.`billdet`.`pbd_totalamount`)) < 12)) AND (((`hid0123_cache_his_dhcapp_sqluser`.`adm`.`paadm_type` = 'I') OR ((`hid0123_cache_his_dhcapp_sqluser`.`adm`.`paadm_type` = 'O') AND (`hid0123_cache_his_dhcapp_sqluser`.`bill`.`pb_payedflag` = 'P'))) OR ((`hid0123_cache_his_dhcapp_sqluser`.`adm`.`paadm_type` = 'E') AND ((`hid0123_cache_his_dhcapp_sqluser`.`bill`.`pb_payedflag` = 'P') OR (`hid0123_cache_his_dhcapp_sqluser`.`adm`.`paadm_currentward_dr` IS NOT NULL)))) AND (`hid0123_cache_his_dhcapp_sqluser`.`ctloc`.`ctloc_hospital_dr` = '2')
GROUP BY `hid0123_cache_his_dhcapp_sqluser`.`billdet`.`pbd_createdate`, `hid0123_cache_his_dhcapp_sqluser`.`adm`.`paadm_type`, `hid0123_cache_his_dhcapp_sqluser`.`tarec`.`tartec_desc`, `hid0123_cache_his_dhcapp_sqluser`.`ctloc`.`ctloc_code`, `hid0123_cache_his_dhcapp_sqluser`.`ctloc`.`ctloc_desc`, `hid0123_cache_his_dhcapp_sqluser`.`ctlocjs`.`ctloc_code`, `hid0123_cache_his_dhcapp_sqluser`.`ctlocjs`.`ctloc_desc`, `hid0123_cache_his_dhcapp_sqluser`.`ctlocjzks`.`ctloc_desc`, `hid0123_cache_his_dhcapp_sqluser`.`zyward`.`ward_desc`, `hid0123_cache_his_dhcapp_sqluser`.`ctlocjzks`.`ctloc_code`, `hid0123_cache_his_dhcapp_sqluser`.`zyward`.`ward_code` UNION ALL SELECT 'HID0124' AS `hosp_code`, `hid0123_cache_his_dhcapp_sqluser`.`billdet`.`pbd_createdate` AS `abdate`, `hid0123_cache_his_dhcapp_sqluser`.`adm`.`paadm_type` AS `paadmtype`, `hid0123_cache_his_dhcapp_sqluser`.`tarec`.`tartec_desc` AS `tectype`, `hid0123_cache_his_dhcapp_sqluser`.`ctloc`.`ctloc_code` AS `ordloc_code`, `hid0123_cache_his_dhcapp_sqluser`.`ctloc`.`ctloc_desc` AS `ordloc`, `hid0123_cache_his_dhcapp_sqluser`.`ctlocjs`.`ctloc_code` AS `recloc_code`, `hid0123_cache_his_dhcapp_sqluser`.`ctlocjs`.`ctloc_desc` AS `recloc`, `hid0123_cache_his_dhcapp_sqluser`.`ctlocjzks`.`ctloc_code` AS `patloccode`, `hid0123_cache_his_dhcapp_sqluser`.`ctlocjzks`.`ctloc_desc` AS `patloc`, `hid0123_cache_his_dhcapp_sqluser`.`zyward`.`ward_code` AS `patwardcode`, `hid0123_cache_his_dhcapp_sqluser`.`zyward`.`ward_desc` AS `patward`, CAST((sum(CASE WHEN ((abs(CAST(`hid0123_cache_his_dhcapp_sqluser`.`billdet`.`pbd_totalamount` AS DECIMAL64(18,4)))) > (abs((CAST(`hid0123_cache_his_dhcapp_sqluser`.`billdet`.`pbd_totalamount` AS DECIMAL64(18,4))) - (coalesce(CAST(`hid0123_cache_his_dhcapp_sqluser`.`billdet`.`pbd_discamount` AS DECIMAL64(18,4)), 0))))) THEN (CAST(`hid0123_cache_his_dhcapp_sqluser`.`billdet`.`pbd_totalamount` AS DECIMAL64(18,4))) ELSE ((CAST(`hid0123_cache_his_dhcapp_sqluser`.`billdet`.`pbd_totalamount` AS DECIMAL64(18,4))) - (coalesce(CAST(`hid0123_cache_his_dhcapp_sqluser`.`billdet`.`pbd_discamount` AS DECIMAL64(18,4)), 0))) END)) AS DOUBLE) AS `totalfee`, current_timestamp() AS `lastupdatedttm`
FROM `hid0123_cache_his_dhcapp_sqluser`.`dhc_patbilldetails` AS `billdet` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`dhc_patbillorder` AS `pbo` ON `hid0123_cache_his_dhcapp_sqluser`.`billdet`.`pbd_pbo_parref` = `hid0123_cache_his_dhcapp_sqluser`.`pbo`.`pbo_rowid` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`dhc_patientbill` AS `bill` ON `hid0123_cache_his_dhcapp_sqluser`.`bill`.`pb_rowid` = `hid0123_cache_his_dhcapp_sqluser`.`pbo`.`pbo_pb_parref` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`pa_adm` AS `adm` ON `hid0123_cache_his_dhcapp_sqluser`.`bill`.`pb_adm_dr` = `hid0123_cache_his_dhcapp_sqluser`.`adm`.`paadm_rowid` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`dhc_taritem` AS `taritem` ON `hid0123_cache_his_dhcapp_sqluser`.`billdet`.`pbd_tari_dr` = `hid0123_cache_his_dhcapp_sqluser`.`taritem`.`tari_rowid` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`dhc_taremccate` AS `taremc` ON `hid0123_cache_his_dhcapp_sqluser`.`taritem`.`tari_emccate` = `hid0123_cache_his_dhcapp_sqluser`.`taremc`.`tarec_rowid` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`dhc_tarec` AS `tarec` ON `hid0123_cache_his_dhcapp_sqluser`.`tarec`.`tartec_rowid` = `hid0123_cache_his_dhcapp_sqluser`.`taremc`.`tarec_tartec_dr` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`oe_orditem` AS `oeori` ON `hid0123_cache_his_dhcapp_sqluser`.`oeori`.`oeori_rowid` = `hid0123_cache_his_dhcapp_sqluser`.`pbo`.`pbo_oeori_dr` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`ct_loc` AS `ctloc` ON `hid0123_cache_his_dhcapp_sqluser`.`oeori`.`oeori_orddept_dr` = `hid0123_cache_his_dhcapp_sqluser`.`ctloc`.`ctloc_rowid` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`ct_loc` AS `ctlocjs` ON `hid0123_cache_his_dhcapp_sqluser`.`oeori`.`oeori_recdep_dr` = `hid0123_cache_his_dhcapp_sqluser`.`ctlocjs`.`ctloc_rowid` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`ct_loc` AS `ctlocjzks` ON `hid0123_cache_his_dhcapp_sqluser`.`adm`.`paadm_depcode_dr` = `hid0123_cache_his_dhcapp_sqluser`.`ctlocjzks`.`ctloc_rowid` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`pac_ward` AS `zyward` ON `hid0123_cache_his_dhcapp_sqluser`.`adm`.`paadm_currentward_dr` = `hid0123_cache_his_dhcapp_sqluser`.`zyward`.`ward_rowid`
WHERE (((`hid0123_cache_his_dhcapp_sqluser`.`billdet`.`pbd_createdate` = (CAST((current_date()) AS VARCHAR))) AND (`hid0123_cache_his_dhcapp_sqluser`.`billdet`.`isdeleted` = '0')) AND ((length(`hid0123_cache_his_dhcapp_sqluser`.`billdet`.`pbd_totalamount`)) < 12)) AND (((`hid0123_cache_his_dhcapp_sqluser`.`adm`.`paadm_type` = 'I') OR ((`hid0123_cache_his_dhcapp_sqluser`.`adm`.`paadm_type` = 'O') AND (`hid0123_cache_his_dhcapp_sqluser`.`bill`.`pb_payedflag` = 'P'))) OR ((`hid0123_cache_his_dhcapp_sqluser`.`adm`.`paadm_type` = 'E') AND ((`hid0123_cache_his_dhcapp_sqluser`.`bill`.`pb_payedflag` = 'P') OR (`hid0123_cache_his_dhcapp_sqluser`.`adm`.`paadm_currentward_dr` IS NOT NULL)))) AND (`hid0123_cache_his_dhcapp_sqluser`.`ctloc`.`ctloc_hospital_dr` = '12')
GROUP BY `hid0123_cache_his_dhcapp_sqluser`.`billdet`.`pbd_createdate`, `hid0123_cache_his_dhcapp_sqluser`.`adm`.`paadm_type`, `hid0123_cache_his_dhcapp_sqluser`.`tarec`.`tartec_desc`, `hid0123_cache_his_dhcapp_sqluser`.`ctloc`.`ctloc_code`, `hid0123_cache_his_dhcapp_sqluser`.`ctloc`.`ctloc_desc`, `hid0123_cache_his_dhcapp_sqluser`.`ctlocjs`.`ctloc_code`, `hid0123_cache_his_dhcapp_sqluser`.`ctlocjs`.`ctloc_desc`, `hid0123_cache_his_dhcapp_sqluser`.`ctlocjzks`.`ctloc_desc`, `hid0123_cache_his_dhcapp_sqluser`.`zyward`.`ward_desc`, `hid0123_cache_his_dhcapp_sqluser`.`ctlocjzks`.`ctloc_code`, `hid0123_cache_his_dhcapp_sqluser`.`zyward`.`ward_code`;

CREATE MATERIALIZED VIEW `indicators`.`mzssxz_indicators_v3` (`hosp_code`, `ctloc_desc`, `ctloc_code`, `questatedr`, `paadm_type`, `ghl`, `lastupdatedttm`)
COMMENT "实时就诊挂号"
DISTRIBUTED BY HASH(`hosp_code`)
REFRESH ASYNC EVERY(INTERVAL 180 SECOND)
PROPERTIES (
"replicated_storage" = "true",
"replication_num" = "3",
"storage_medium" = "HDD"
)
AS SELECT 'HID0101' AS `hosp_code`, `hid0101_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0101_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0101_cache_his_dhcapp_sqluser`.`a`.`questatedr`, `hid0101_cache_his_dhcapp_sqluser`.`adm`.`paadm_type`, count(1) AS `ghl`, current_timestamp() AS `lastupdatedttm`
FROM `hid0101_cache_his_dhcapp_sqluser`.`dhcqueue` AS `a` LEFT OUTER JOIN `hid0101_cache_his_dhcapp_sqluser`.`ct_loc` AS `b` ON `hid0101_cache_his_dhcapp_sqluser`.`a`.`quedepdr` = `hid0101_cache_his_dhcapp_sqluser`.`b`.`ctloc_rowid` LEFT OUTER JOIN `hid0101_cache_his_dhcapp_sqluser`.`pa_adm` AS `adm` ON `hid0101_cache_his_dhcapp_sqluser`.`adm`.`paadm_rowid` = `hid0101_cache_his_dhcapp_sqluser`.`a`.`quepaadmdr`
WHERE (((((CAST(`hid0101_cache_his_dhcapp_sqluser`.`a`.`quedate` AS VARCHAR)) = (substring(CAST((current_timestamp()) AS VARCHAR), 1, 10))) AND (`hid0101_cache_his_dhcapp_sqluser`.`a`.`questatedr` IN ('1', '2', '3', '4', '6', '7'))) AND (`hid0101_cache_his_dhcapp_sqluser`.`a`.`queno` != '')) AND (NOT (`hid0101_cache_his_dhcapp_sqluser`.`a`.`queno` LIKE '%慢%'))) AND ((CAST(`hid0101_cache_his_dhcapp_sqluser`.`adm`.`paadm_admdate` AS VARCHAR)) = (substring(CAST((current_timestamp()) AS VARCHAR), 1, 10)))
GROUP BY `hid0101_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0101_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0101_cache_his_dhcapp_sqluser`.`a`.`questatedr`, `hid0101_cache_his_dhcapp_sqluser`.`adm`.`paadm_type` UNION ALL SELECT 'HID0103' AS `hosp_code`, `hid0103_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0103_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0103_cache_his_dhcapp_sqluser`.`a`.`questatedr`, `hid0103_cache_his_dhcapp_sqluser`.`adm`.`paadm_type`, count(1) AS `ghl`, current_timestamp() AS `lastupdatedttm`
FROM `hid0103_cache_his_dhcapp_sqluser`.`dhcqueue` AS `a` LEFT OUTER JOIN `hid0103_cache_his_dhcapp_sqluser`.`ct_loc` AS `b` ON `hid0103_cache_his_dhcapp_sqluser`.`a`.`quedepdr` = `hid0103_cache_his_dhcapp_sqluser`.`b`.`ctloc_rowid` LEFT OUTER JOIN `hid0103_cache_his_dhcapp_sqluser`.`pa_adm` AS `adm` ON `hid0103_cache_his_dhcapp_sqluser`.`adm`.`paadm_rowid` = `hid0103_cache_his_dhcapp_sqluser`.`a`.`quepaadmdr`
WHERE (((((CAST(`hid0103_cache_his_dhcapp_sqluser`.`a`.`quedate` AS VARCHAR)) = (substring(CAST((current_timestamp()) AS VARCHAR), 1, 10))) AND (`hid0103_cache_his_dhcapp_sqluser`.`a`.`questatedr` IN ('1', '2', '3', '4', '6', '7'))) AND (`hid0103_cache_his_dhcapp_sqluser`.`a`.`queno` != '')) AND (NOT (`hid0103_cache_his_dhcapp_sqluser`.`a`.`queno` LIKE '%慢%'))) AND ((CAST(`hid0103_cache_his_dhcapp_sqluser`.`adm`.`paadm_admdate` AS VARCHAR)) = (substring(CAST((current_timestamp()) AS VARCHAR), 1, 10)))
GROUP BY `hid0103_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0103_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0103_cache_his_dhcapp_sqluser`.`a`.`questatedr`, `hid0103_cache_his_dhcapp_sqluser`.`adm`.`paadm_type` UNION ALL SELECT 'HID0117' AS `hosp_code`, `hid0117_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0117_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0117_cache_his_dhcapp_sqluser`.`a`.`questatedr`, `hid0117_cache_his_dhcapp_sqluser`.`adm`.`paadm_type`, count(1) AS `ghl`, current_timestamp() AS `lastupdatedttm`
FROM `hid0117_cache_his_dhcapp_sqluser`.`dhcqueue` AS `a` LEFT OUTER JOIN `hid0117_cache_his_dhcapp_sqluser`.`ct_loc` AS `b` ON `hid0117_cache_his_dhcapp_sqluser`.`a`.`quedepdr` = `hid0117_cache_his_dhcapp_sqluser`.`b`.`ctloc_rowid` LEFT OUTER JOIN `hid0117_cache_his_dhcapp_sqluser`.`pa_adm` AS `adm` ON `hid0117_cache_his_dhcapp_sqluser`.`adm`.`paadm_rowid` = `hid0117_cache_his_dhcapp_sqluser`.`a`.`quepaadmdr`
WHERE (((((CAST(`hid0117_cache_his_dhcapp_sqluser`.`a`.`quedate` AS VARCHAR)) = (substring(CAST((current_timestamp()) AS VARCHAR), 1, 10))) AND (`hid0117_cache_his_dhcapp_sqluser`.`a`.`questatedr` IN ('1', '2', '3', '4', '6', '7'))) AND (`hid0117_cache_his_dhcapp_sqluser`.`a`.`queno` != '')) AND (NOT (`hid0117_cache_his_dhcapp_sqluser`.`a`.`queno` LIKE '%慢%'))) AND ((CAST(`hid0117_cache_his_dhcapp_sqluser`.`adm`.`paadm_admdate` AS VARCHAR)) = (substring(CAST((current_timestamp()) AS VARCHAR), 1, 10)))
GROUP BY `hid0117_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0117_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0117_cache_his_dhcapp_sqluser`.`a`.`questatedr`, `hid0117_cache_his_dhcapp_sqluser`.`adm`.`paadm_type` UNION ALL SELECT 'HID0120' AS `hosp_code`, `hid0120_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0120_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0120_cache_his_dhcapp_sqluser`.`a`.`questatedr`, `hid0120_cache_his_dhcapp_sqluser`.`adm`.`paadm_type`, count(1) AS `ghl`, current_timestamp() AS `lastupdatedttm`
FROM `hid0120_cache_his_dhcapp_sqluser`.`dhcqueue` AS `a` LEFT OUTER JOIN `hid0120_cache_his_dhcapp_sqluser`.`ct_loc` AS `b` ON `hid0120_cache_his_dhcapp_sqluser`.`a`.`quedepdr` = `hid0120_cache_his_dhcapp_sqluser`.`b`.`ctloc_rowid` LEFT OUTER JOIN `hid0120_cache_his_dhcapp_sqluser`.`pa_adm` AS `adm` ON `hid0120_cache_his_dhcapp_sqluser`.`adm`.`paadm_rowid` = `hid0120_cache_his_dhcapp_sqluser`.`a`.`quepaadmdr`
WHERE (((((CAST(`hid0120_cache_his_dhcapp_sqluser`.`a`.`quedate` AS VARCHAR)) = (substring(CAST((current_timestamp()) AS VARCHAR), 1, 10))) AND (`hid0120_cache_his_dhcapp_sqluser`.`a`.`questatedr` IN ('1', '2', '3', '4', '6', '7'))) AND (`hid0120_cache_his_dhcapp_sqluser`.`a`.`queno` != '')) AND (NOT (`hid0120_cache_his_dhcapp_sqluser`.`a`.`queno` LIKE '%慢%'))) AND ((CAST(`hid0120_cache_his_dhcapp_sqluser`.`adm`.`paadm_admdate` AS VARCHAR)) = (substring(CAST((current_timestamp()) AS VARCHAR), 1, 10)))
GROUP BY `hid0120_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0120_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0120_cache_his_dhcapp_sqluser`.`a`.`questatedr`, `hid0120_cache_his_dhcapp_sqluser`.`adm`.`paadm_type` UNION ALL SELECT 'HID0122' AS `hosp_code`, `hid0122_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0122_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0122_cache_his_dhcapp_sqluser`.`a`.`questatedr`, `hid0122_cache_his_dhcapp_sqluser`.`adm`.`paadm_type`, count(1) AS `ghl`, current_timestamp() AS `lastupdatedttm`
FROM `hid0122_cache_his_dhcapp_sqluser`.`dhcqueue` AS `a` LEFT OUTER JOIN `hid0122_cache_his_dhcapp_sqluser`.`ct_loc` AS `b` ON `hid0122_cache_his_dhcapp_sqluser`.`a`.`quedepdr` = `hid0122_cache_his_dhcapp_sqluser`.`b`.`ctloc_rowid` LEFT OUTER JOIN `hid0122_cache_his_dhcapp_sqluser`.`pa_adm` AS `adm` ON `hid0122_cache_his_dhcapp_sqluser`.`adm`.`paadm_rowid` = `hid0122_cache_his_dhcapp_sqluser`.`a`.`quepaadmdr`
WHERE (((((CAST(`hid0122_cache_his_dhcapp_sqluser`.`a`.`quedate` AS VARCHAR)) = (substring(CAST((current_timestamp()) AS VARCHAR), 1, 10))) AND (`hid0122_cache_his_dhcapp_sqluser`.`a`.`questatedr` IN ('1', '2', '3', '4', '6', '7'))) AND (`hid0122_cache_his_dhcapp_sqluser`.`a`.`queno` != '')) AND (NOT (`hid0122_cache_his_dhcapp_sqluser`.`a`.`queno` LIKE '%慢%'))) AND ((CAST(`hid0122_cache_his_dhcapp_sqluser`.`adm`.`paadm_admdate` AS VARCHAR)) = (substring(CAST((current_timestamp()) AS VARCHAR), 1, 10)))
GROUP BY `hid0122_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0122_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0122_cache_his_dhcapp_sqluser`.`a`.`questatedr`, `hid0122_cache_his_dhcapp_sqluser`.`adm`.`paadm_type` UNION ALL SELECT 'HID0123' AS `hosp_code`, `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0123_cache_his_dhcapp_sqluser`.`a`.`questatedr`, `hid0123_cache_his_dhcapp_sqluser`.`adm`.`paadm_type`, count(1) AS `ghl`, current_timestamp() AS `lastupdatedttm`
FROM `hid0123_cache_his_dhcapp_sqluser`.`dhcqueue` AS `a` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`ct_loc` AS `b` ON `hid0123_cache_his_dhcapp_sqluser`.`a`.`quedepdr` = `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_rowid` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`pa_adm` AS `adm` ON `hid0123_cache_his_dhcapp_sqluser`.`adm`.`paadm_rowid` = `hid0123_cache_his_dhcapp_sqluser`.`a`.`quepaadmdr`
WHERE (((((CAST(`hid0123_cache_his_dhcapp_sqluser`.`a`.`quedate` AS VARCHAR)) = (substring(CAST((current_timestamp()) AS VARCHAR), 1, 10))) AND (`hid0123_cache_his_dhcapp_sqluser`.`a`.`questatedr` IN ('1', '2', '3', '4', '6', '7'))) AND (`hid0123_cache_his_dhcapp_sqluser`.`a`.`queno` != '')) AND (NOT (`hid0123_cache_his_dhcapp_sqluser`.`a`.`queno` LIKE '%慢%'))) AND ((CAST(`hid0123_cache_his_dhcapp_sqluser`.`adm`.`paadm_admdate` AS VARCHAR)) = (substring(CAST((current_timestamp()) AS VARCHAR), 1, 10))) AND (`hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_hospital_dr` = '2')
GROUP BY `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0123_cache_his_dhcapp_sqluser`.`a`.`questatedr`, `hid0123_cache_his_dhcapp_sqluser`.`adm`.`paadm_type` UNION ALL SELECT 'HID0124' AS `hosp_code`, `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0123_cache_his_dhcapp_sqluser`.`a`.`questatedr`, `hid0123_cache_his_dhcapp_sqluser`.`adm`.`paadm_type`, count(1) AS `ghl`, current_timestamp() AS `lastupdatedttm`
FROM `hid0123_cache_his_dhcapp_sqluser`.`dhcqueue` AS `a` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`ct_loc` AS `b` ON `hid0123_cache_his_dhcapp_sqluser`.`a`.`quedepdr` = `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_rowid` LEFT OUTER JOIN `hid0123_cache_his_dhcapp_sqluser`.`pa_adm` AS `adm` ON `hid0123_cache_his_dhcapp_sqluser`.`adm`.`paadm_rowid` = `hid0123_cache_his_dhcapp_sqluser`.`a`.`quepaadmdr`
WHERE (((((CAST(`hid0123_cache_his_dhcapp_sqluser`.`a`.`quedate` AS VARCHAR)) = (substring(CAST((current_timestamp()) AS VARCHAR), 1, 10))) AND (`hid0123_cache_his_dhcapp_sqluser`.`a`.`questatedr` IN ('1', '2', '3', '4', '6', '7'))) AND (`hid0123_cache_his_dhcapp_sqluser`.`a`.`queno` != '')) AND (NOT (`hid0123_cache_his_dhcapp_sqluser`.`a`.`queno` LIKE '%慢%'))) AND ((CAST(`hid0123_cache_his_dhcapp_sqluser`.`adm`.`paadm_admdate` AS VARCHAR)) = (substring(CAST((current_timestamp()) AS VARCHAR), 1, 10))) AND (`hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_hospital_dr` = '12')
GROUP BY `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_desc`, `hid0123_cache_his_dhcapp_sqluser`.`b`.`ctloc_code`, `hid0123_cache_his_dhcapp_sqluser`.`a`.`questatedr`, `hid0123_cache_his_dhcapp_sqluser`.`adm`.`paadm_type`;


-- =============================================================================

USE indicators;

-- 1）列出 indicators 库下全部异步物化视图（名称、刷新状态、行数等）
SHOW MATERIALIZED VIEWS FROM indicators;

-- 2）仅查 _v3 / _v2 物化视图
SHOW MATERIALIZED VIEWS FROM indicators
WHERE NAME LIKE '%_v3' OR NAME LIKE '%_v2';

-- 3）information_schema 明细（含最近刷新时间、状态、错误信息）
SELECT
    TABLE_SCHEMA,
    TABLE_NAME,
    REFRESH_TYPE,
    IS_ACTIVE,
    LAST_REFRESH_STATE,
    LAST_REFRESH_START_TIME,
    LAST_REFRESH_FINISHED_TIME,
    LAST_REFRESH_ERROR_MESSAGE,
    ROWS
FROM information_schema.materialized_views
WHERE TABLE_SCHEMA = 'indicators'
ORDER BY TABLE_NAME;

-- 4）按院区抽样（含 HID0122/HID0123/HID0124 公卫）
SELECT 'currentcyxz_v3' AS mv, hosp_code, count(*) AS cnt FROM indicators.currentcyxz_v3 GROUP BY hosp_code
UNION ALL
SELECT 'currentryxz_v3', hosp_code, count(*) FROM indicators.currentryxz_v3 GROUP BY hosp_code
UNION ALL
SELECT 'currentzyxz_v3', hosp_code, count(*) FROM indicators.currentzyxz_v3 GROUP BY hosp_code
UNION ALL
SELECT 'currtime_income_v3', hosp_code, count(*) FROM indicators.currtime_income_v3 GROUP BY hosp_code
UNION ALL
SELECT 'mzssxz_indicators_v3', hosp_code, count(*) FROM indicators.mzssxz_indicators_v3 GROUP BY hosp_code;

-- 5）单表预览（按需执行）
-- SELECT * FROM indicators.currentcyxz_v3 LIMIT 20;
-- SELECT * FROM indicators.currentryxz_v3 LIMIT 20;
-- SELECT * FROM indicators.currentzyxz_v3 LIMIT 20;
-- SELECT * FROM indicators.currtime_income_v3 LIMIT 20;
-- SELECT * FROM indicators.fsjcl_v2 LIMIT 20;
-- SELECT * FROM indicators.jfyjgzl_v2 LIMIT 20;
-- SELECT * FROM indicators.kdyjgzl_v2 LIMIT 20;
-- SELECT * FROM indicators.mzssxz_indicators_v3 LIMIT 20;

-- 6）手动触发刷新（异常排查时用，按需取消注释）
-- REFRESH MATERIALIZED VIEW indicators.currentcyxz_v3;
-- REFRESH MATERIALIZED VIEW indicators.currentryxz_v3;
-- REFRESH MATERIALIZED VIEW indicators.currentzyxz_v3;
-- REFRESH MATERIALIZED VIEW indicators.currtime_income_v3;
-- REFRESH MATERIALIZED VIEW indicators.fsjcl_v2;
-- REFRESH MATERIALIZED VIEW indicators.jfyjgzl_v2;
-- REFRESH MATERIALIZED VIEW indicators.kdyjgzl_v2;
-- REFRESH MATERIALIZED VIEW indicators.mzssxz_indicators_v3;
